apiVersion: v1
kind: Pod
metadata:
   name: nginx
spec:
  volumes:
    - name: "appdata"
      persistentVolumeClaim:
         claimName: "azure-premium-disk"
  containers:
    - image: nginx:latest
      name: nginx
      volumeMounts:
        - mountPath: "/data"
          name: "appdata"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
