apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-premium-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 2Gi
