kind: ConfigMap
apiVersion: v1
data:
  schema-version: 
    #string.used by agent to parse config. supported versions are {v1, v2}. Configs with other schema versions will be rejected by the agent.
    v2
  config-version: 
    #string.used by customer to keep track of this config file's version in their source control/repository (max allowed 10 chars, other chars will be truncated)
    ver1
  dataplane-metrics: |-
    default-scrape-settings-enabled: |-
      kubelet = true
      coredns = false
      cadvisor = true
      kubeproxy = false
      kubestate = true
      nodeexporter = true
      windowsexporter = false
      windowskubeproxy = false
      kappiebasic = true
      networkobservabilityRetina = true
      networkobservabilityHubble = true
      networkobservabilityCilium = true
      prometheuscollectorhealth = false
    pod-annotation-based-scraping: |-
      podannotationnamespaceregex = ""
    default-targets-metrics-keep-list: |-
      kubelet = ""
      coredns = ""
      cadvisor = ""
      kubeproxy = ""
      apiserver = ""
      kubestate = ""
      nodeexporter = ""
      windowsexporter = ""
      windowskubeproxy = ""
      podannotations = ""
      kappiebasic = ""
      networkobservabilityRetina = ""
      networkobservabilityHubble = ""
      networkobservabilityCilium = ""
      minimalingestionprofile = true
    minimal-ingestion-profile: |-
      enabled = true
    default-targets-scrape-interval-settings: |-
      kubelet = "30s"
      coredns = "30s"
      cadvisor = "30s"
      kubeproxy = "30s"
      apiserver = "30s"
      kubestate = "30s"
      nodeexporter = "30s"
      windowsexporter = "30s"
      windowskubeproxy = "30s"
      kappiebasic = "30s"
      networkobservabilityRetina = "30s"
      networkobservabilityHubble = "30s"
      networkobservabilityCilium = "30s"
      prometheuscollectorhealth = "30s"
      podannotations = "30s"
    debug-mode: |-
      enabled = false 
  controlplane-metrics: |-
    default-scrape-settings-enabled: |-
      apiserver = true
      cluster-autoscaler = false
      kube-scheduler = false
      kube-controller-manager = false
      etcd = true
    default-targets-metrics-keep-list: |-
      apiserver = ""
      cluster-autoscaler = ""
      kube-scheduler = ""
      kube-controller-manager = ""
      etcd = ""
    minimal-ingestion-profile: |-
      enabled = true
  shared: |-
    prometheus-collector-settings: |-
      cluster_alias = ""
metadata:
  name: ama-metrics-settings-configmap
  namespace: kube-system