{
 "title": "Kubernetes / API server",
 "description": "Source-https://github.com/monitoring-mixins/website/blob/master/assets/kubernetes/dashboards/apiserver.json",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(apiserver_request_total, cluster)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(apiserver_request_total{job=\"kube-apiserver\", cluster=\"$cluster\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Notice",
   "type": "text",
   "description": "The SLO (service level objective) and other metrics displayed on this dashboard are for informational purposes only.",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "The SLO (service level objective) and other metrics displayed on this dashboard are for informational purposes only."
   }
  },
  {
   "title": "Availability (13d) > 99.000%",
   "type": "stat",
   "description": "How many percent of requests (both read and write) in 30 days have been answered successfully and fast enough?",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\r\n 1 - (\r\n          (\r\n            # write too slow\r\n            sum(increase(apiserver_request_duration_seconds_count{job=\"kube-apiserver\",verb=~\"POST|PUT|PATCH|DELETE\",cluster=\"$cluster\",instance=~\"$instance\"}[13d]))\r\n            -\r\n            sum(increase(apiserver_request_duration_seconds_bucket{job=\"kube-apiserver\",verb=~\"POST|PUT|PATCH|DELETE\",le=\"1\",cluster=\"$cluster\",instance=~\"$instance\"}[13d]))\r\n          ) +\r\n          (\r\n            # read too slow\r\n            sum(increase(apiserver_request_duration_seconds_count{job=\"kube-apiserver\",verb=~\"LIST|GET\",cluster=\"$cluster\",instance=~\"$instance\"}[13d]))\r\n            -\r\n            (\r\n              sum(increase(apiserver_request_duration_seconds_bucket{job=\"kube-apiserver\",verb=~\"LIST|GET\",scope=\"resource\",le=\"0.1\",cluster=\"$cluster\",instance=~\"$instance\"}[13d]) or vector(0) )   +\r\n              sum(increase(apiserver_request_duration_seconds_bucket{job=\"kube-apiserver\",verb=~\"LIST|GET\",scope=\"namespace\",le=\"0.5\",cluster=\"$cluster\",instance=~\"$instance\"}[13d]))  +\r\n              sum(increase(apiserver_request_duration_seconds_bucket{job=\"kube-apiserver\",verb=~\"LIST|GET\",scope=\"cluster\",le=\"5\",cluster=\"$cluster\",instance=~\"$instance\"}[13d]))\r\n            )\r\n          ) +\r\n          # errors\r\n          sum(sum by (code) (sum by (code, verb) (increase(apiserver_request_total{job=\"kube-apiserver\",cluster=\"$cluster\",verb=~\"LIST|GET|POST|PUT|PATCH|DELETE\",code=~\"5..\",instance=~\"$instance\"}[13d]))) or vector(0) ) \r\n        )\r\n        /\r\n        sum(sum by (code) (sum by (code, verb) (increase(apiserver_request_total{job=\"kube-apiserver\",cluster=\"$cluster\",instance=~\"$instance\"}[13d])) ))"
    }
   ]
  },
  {
   "title": "ErrorBudget (13d) > 99.000%",
   "type": "graph",
   "description": "How much error budget is left looking at our 0.990% availability guarantees?",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * ( \t1 - (\r\n\t          (\r\n\t            # write too slow\r\n\t            sum(increase(apiserver_request_duration_seconds_count{job=\"kube-apiserver\",verb=~\"POST|PUT|PATCH|DELETE\",cluster=\"$cluster\",instance=~\"$instance\"}[13d]))\r\n\t            -\r\n\t            sum(increase(apiserver_request_duration_seconds_bucket{job=\"kube-apiserver\",verb=~\"POST|PUT|PATCH|DELETE\",le=\"1\",cluster=\"$cluster\",instance=~\"$instance\"}[13d]))\r\n\t          ) +\r\n\t          (\r\n\t            # read too slow\r\n\t            sum(increase(apiserver_request_duration_seconds_count{job=\"kube-apiserver\",verb=~\"LIST|GET\",cluster=\"$cluster\",instance=~\"$instance\"}[13d]))\r\n\t            -\r\n\t            (\r\n\t              sum(increase(apiserver_request_duration_seconds_bucket{job=\"kube-apiserver\",verb=~\"LIST|GET\",scope=\"resource\",le=\"0.1\",cluster=\"$cluster\",instance=~\"$instance\"}[13d]) or vector(0) )  +\r\n\t              sum(increase(apiserver_request_duration_seconds_bucket{job=\"kube-apiserver\",verb=~\"LIST|GET\",scope=\"namespace\",le=\"0.5\",cluster=\"$cluster\",instance=~\"$instance\"}[13d]))  +\r\n\t              sum(increase(apiserver_request_duration_seconds_bucket{job=\"kube-apiserver\",verb=~\"LIST|GET\",scope=\"cluster\",le=\"5\",cluster=\"$cluster\",instance=~\"$instance\"}[13d]))\r\n\t            )\r\n\t          ) +\r\n\t          # errors\r\n\t          sum(sum by (code) (sum by (code, verb) (increase(apiserver_request_total{job=\"kube-apiserver\",cluster=\"$cluster\",verb=~\"LIST|GET|POST|PUT|PATCH|DELETE\",code=~\"5..\",instance=~\"$instance\"}[13d]))) or vector(0) )\r\n\t        )\r\n\t        /\r\n\t        sum(sum by (code) (sum by (code, verb) (increase(apiserver_request_total{job=\"kube-apiserver\",cluster=\"$cluster\",instance=~\"$instance\"}[13d])) ))\r\n - 0.990000)",
     "legendFormat": "errorbudget"
    }
   ]
  },
  {
   "title": "Read Availability (13d)",
   "type": "stat",
   "description": "How many percent of read requests (LIST,GET) in 30 days have been answered successfully and fast enough?",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " 1 - (\r\n            # read too slow\r\n            sum(increase(apiserver_request_duration_seconds_count{job=\"kube-apiserver\",verb=~\"LIST|GET\",cluster=\"$cluster\",instance=~\"$instance\"}[13d]))\r\n            -\r\n            (\r\n              sum(increase(apiserver_request_duration_seconds_bucket{job=\"kube-apiserver\",verb=~\"LIST|GET\",scope=\"resource\",le=\"0.1\",cluster=\"$cluster\",instance=~\"$instance\"}[13d]) or vector(0) )   +\r\n              sum(increase(apiserver_request_duration_seconds_bucket{job=\"kube-apiserver\",verb=~\"LIST|GET\",scope=\"namespace\",le=\"0.5\",cluster=\"$cluster\",instance=~\"$instance\"}[13d]))  +\r\n              sum(increase(apiserver_request_duration_seconds_bucket{job=\"kube-apiserver\",verb=~\"LIST|GET\",scope=\"cluster\",le=\"5\",cluster=\"$cluster\",instance=~\"$instance\"}[13d]))\r\n            )\r\n            +\r\n            # errors\r\n            sum(sum by (code) (sum by (code, verb) (increase(apiserver_request_total{job=\"kube-apiserver\",cluster=\"$cluster\",verb=~\"LIST|GET\",code=~\"5..\",instance=~\"$instance\"}[13d]))) or vector(0) ) \r\n        )\r\n        /\r\n        sum(sum by (code) (sum by (code, verb) (increase(apiserver_request_total{job=\"kube-apiserver\",cluster=\"$cluster\",verb=~\"LIST|GET\",instance=~\"$instance\"}[13d])) ))"
    }
   ]
  },
  {
   "title": "Read SLI - Requests",
   "type": "graph",
   "description": "How many read requests (LIST,GET) per second do the apiservers get by code?",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (sum by (code,resource) (rate(apiserver_request_total{job=\"kube-apiserver\",verb=~\"LIST|GET\",cluster=\"$cluster\",instance=~\"$instance\"}[5m])))",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Read SLI - Errors",
   "type": "graph",
   "description": "How many percent of read requests (LIST,GET) per second are returned with errors (5xx)?",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (resource) (sum by (code,resource) (rate(apiserver_request_total{job=\"kube-apiserver\",verb=~\"LIST|GET\",code=~\"5..\", cluster=\"$cluster\",instance=~\"$instance\"}[5m])) or vector(0) ) / sum by (resource) (sum by (code,resource) (rate(apiserver_request_total{job=\"kube-apiserver\",verb=~\"LIST|GET\",cluster=\"$cluster\",instance=~\"$instance\"}[5m])) or vector(0))",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "Read SLI - Duration",
   "type": "graph",
   "description": "How many seconds is the 99th percentile for reading (LIST|GET) a given resource?",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, resource) (rate(apiserver_request_duration_seconds_bucket{job=\"kube-apiserver\",verb=~\"LIST|GET\",cluster=\"$cluster\",instance=~\"$instance\"}[5m]))) > 0",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "Write Availability (13d)",
   "type": "stat",
   "description": "How many percent of write requests (POST|PUT|PATCH|DELETE) in 30 days have been answered successfully and fast enough?",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - (\r\n            # write too slow\r\n            sum(increase(apiserver_request_duration_seconds_count{job=\"kube-apiserver\",verb=~\"POST|PUT|PATCH|DELETE\",cluster=\"$cluster\",instance=~\"$instance\"}[13d]))\r\n            -\r\n            (\r\n              sum(increase(apiserver_request_duration_seconds_bucket{job=\"kube-apiserver\",verb=~\"POST|PUT|PATCH|DELETE\",scope=\"resource\",le=\"0.1\",cluster=\"$cluster\",instance=~\"$instance\"}[13d]) or vector(0) )   +\r\n              sum(increase(apiserver_request_duration_seconds_bucket{job=\"kube-apiserver\",verb=~\"POST|PUT|PATCH|DELETE\",scope=\"namespace\",le=\"0.5\",cluster=\"$cluster\",instance=~\"$instance\"}[13d]))  +\r\n              sum(increase(apiserver_request_duration_seconds_bucket{job=\"kube-apiserver\",verb=~\"POST|PUT|PATCH|DELETE\",scope=\"cluster\",le=\"5\",cluster=\"$cluster\",instance=~\"$instance\"}[13d]))\r\n            )\r\n            +\r\n            # errors\r\n            sum(sum by (code) (sum by (code, verb) (increase(apiserver_request_total{job=\"kube-apiserver\",cluster=\"$cluster\",verb=~\"POST|PUT|PATCH|DELETE\",code=~\"5..\",instance=~\"$instance\"}[13d]))) or vector(0) ) \r\n        )\r\n        /\r\n        sum(sum by (code) (sum by (code, verb) (increase(apiserver_request_total{job=\"kube-apiserver\",cluster=\"$cluster\",verb=~\"POST|PUT|PATCH|DELETE\",instance=~\"$instance\"}[13d])) ))"
    }
   ]
  },
  {
   "title": "Write SLI - Requests",
   "type": "graph",
   "description": "How many write requests (POST|PUT|PATCH|DELETE) per second do the apiservers get by code?",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (sum by (code,resource) (rate(apiserver_request_total{job=\"kube-apiserver\",verb=~\"POST|PUT|PATCH|DELETE\",cluster=\"$cluster\",instance=~\"$instance\"}[5m])))",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Write SLI - Errors",
   "type": "graph",
   "description": "How many percent of write requests (POST|PUT|PATCH|DELETE) per second are returned with errors (5xx)?",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (resource) (sum by (code,resource) (rate(apiserver_request_total{job=\"kube-apiserver\",verb=~\"POST|PUT|PATCH|DELETE\",code=~\"5..\", cluster=\"$cluster\",instance=~\"$instance\"}[5m])) or vector(0) ) / sum by (resource) (sum by (code,resource) (rate(apiserver_request_total{job=\"kube-apiserver\",verb=~\"POST|PUT|PATCH|DELETE\",cluster=\"$cluster\",instance=~\"$instance\"}[5m])) or vector(0))",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "Write SLI - Duration",
   "type": "graph",
   "description": "How many seconds is the 99th percentile for writing (POST|PUT|PATCH|DELETE) a given resource?",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, resource) (rate(apiserver_request_duration_seconds_bucket{job=\"kube-apiserver\",verb=~\"POST|PUT|PATCH|DELETE\",cluster=\"$cluster\",instance=~\"$instance\"}[5m]))) > 0",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "Work Queue Add Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=\"kube-apiserver\", instance=~\"$instance\", cluster=\"$cluster\"}[5m])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_depth{job=\"kube-apiserver\", instance=~\"$instance\", cluster=\"$cluster\"}[5m])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"kube-apiserver\", instance=~\"$instance\", cluster=\"$cluster\"}[5m])) by (instance, name, le))",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"kube-apiserver\",instance=~\"$instance\", cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kube-apiserver\",instance=~\"$instance\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"kube-apiserver\",instance=~\"$instance\", cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}