apiVersion: v1
data:
  targetallocator.yaml: |
    allocation_strategy: consistent-hashing
    config:
      scrape_configs:
      - job_name: kubelet
        scheme: https
        metrics_path: /metrics
        scrape_interval: 30s
        label_limit: 63
        label_name_length_limit: 511
        label_value_length_limit: 1023
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
        - source_labels: [__metrics_path__]
          regex: (.*)
          target_label: metrics_path
        - source_labels: [__address__]
          replacement: '$$NODE_NAME'
          target_label: instance
        static_configs:
        - targets: ['$$NODE_IP:10250']
    label_selector:
      app.kubernetes.io/component: opentelemetry-collector
      app.kubernetes.io/instance: kube-system.ama-metrics-otelcollector
      app.kubernetes.io/managed-by: opentelemetry-operator
    pod_monitor_selector:
      component: ds
    service_monitor_selector:
      component: ds
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: opentelemetry-targetallocator-node
    app.kubernetes.io/instance: kube-system.ama-metrics-otelcollector-node
    app.kubernetes.io/managed-by: opentelemetry-operator
    app.kubernetes.io/name: ama-metrics-otelcollector-targetallocator-node
    app.kubernetes.io/part-of: opentelemetry
    app.kubernetes.io/version: 6.7.0-grace-operator-05-24-2023-5950ffab
  name: ama-metrics-otelcollector-targetallocator-node
  namespace: kube-system
