apiVersion: v1
data:
  targetallocator.yaml: |
    allocation_strategy: consistent-hashing
    config:
      scrape_configs:
      - job_name: kube-state-metrics
        label_limit: 63
        label_name_length_limit: 511
        label_value_length_limit: 1023
        metric_relabel_configs:
        - action: keep
          regex: '|kube_job_status_succeeded|kube_job_spec_completions|kube_daemonset_status_desired_number_scheduled|kube_daemonset_status_number_ready|kube_deployment_status_replicas_ready|kube_pod_container_status_last_terminated_reason|kube_pod_container_status_waiting_reason|kube_pod_container_status_restarts_total|kube_node_status_allocatable|kube_pod_owner|kube_pod_container_resource_requests|kube_pod_status_phase|kube_pod_container_resource_limits|kube_replicaset_owner|kube_resourcequota|kube_namespace_status_phase|kube_node_status_capacity|kube_node_info|kube_pod_info|kube_deployment_spec_replicas|kube_deployment_status_replicas_available|kube_deployment_status_replicas_updated|kube_statefulset_status_replicas_ready|kube_statefulset_status_replicas|kube_statefulset_status_replicas_updated|kube_job_status_start_time|kube_job_status_active|kube_job_failed|kube_horizontalpodautoscaler_status_desired_replicas|kube_horizontalpodautoscaler_status_current_replicas|kube_horizontalpodautoscaler_spec_min_replicas|kube_horizontalpodautoscaler_spec_max_replicas|kubernetes_build_info|kube_node_status_condition|kube_node_spec_taint|kube_pod_container_info|kube_.*_labels|kube_.*_annotations'
          source_labels:
          - __name__
        scrape_interval: 30s
        static_configs:
        - targets:
          - ama-metrics-ksm.kube-system.svc.cluster.local:8080
    label_selector:
      app.kubernetes.io/component: opentelemetry-collector
      app.kubernetes.io/instance: kube-system.ama-metrics-otelcollector
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: opentelemetry-targetallocator
    app.kubernetes.io/instance: kube-system.ama-metrics-otelcollector
    app.kubernetes.io/name: ama-metrics-otelcollector-targetallocator
    app.kubernetes.io/part-of: opentelemetry
    app.kubernetes.io/version: 6.7.0-grace-operator-05-24-2023-5950ffab
  name: ama-metrics-otelcollector-targetallocator
  namespace: kube-system
