apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: ama-metrics
    app.kubernetes.io/name: ama-metrics-ksm
    app.kubernetes.io/part-of: ama-metrics-ksm
    app.kubernetes.io/version: 2.12.0
    helm.sh/chart: azure-monitor-metrics-addon-0.1.0
  name: ama-metrics-ksm
  namespace: kube-system
