{{- if .Values.AzureMonitorMetrics.CollectorHPAEnabled}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ama-metrics-hpa
  namespace: kube-system
  labels:
    component: ama-metrics-hpa
    kubernetes.azure.com/managedby: aks
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ama-metrics
  minReplicas: 1
  maxReplicas: 8
  metrics:
    - type: ContainerResource
      containerResource:
        name: memory
        container: prometheus-collector
        target:
          # averageUtilization: 75
          averageValue: 12Gi # resulted in 2 replicas
          # averageValue: 5Gi # resulted in 2 replicas
          type: AverageValue
{{- end }}