kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ama-metrics-secrets-reader
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
