{{- $arcExtensionSettings := include "arc-extension-settings" . | fromYaml }}
{{- if $arcExtensionSettings.operatorEnabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    component: ama-metrics-operator-targets
    kubernetes.azure.com/managedby: aks
  name: ama-metrics-operator-targets
  namespace: kube-system
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: targetallocation
    port: 80
    protocol: TCP
    targetPort: 8080
{{- if .Values.AzureMonitorMetrics.OperatorTargetsHttpsEnabled }}
  - name: targetallocation-https
    port: 443
    protocol: TCP
    targetPort: 8443
{{- end }}
  selector:
    rsName: ama-metrics-operator-targets
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
{{- end }}
