apiVersion: v1
data:
  targetallocator.yaml: |
    allocation_strategy: consistent-hashing
    config:
      scrape_configs:
    label_selector:
      rsName: ama-metrics-targetallocator
      kubernetes.azure.com/managedby: aks
kind: ConfigMap
metadata:
  labels:
    component: ama-metrics-targetallocator
    kubernetes.azure.com/managedby: aks
  name: ama-metrics-targetallocator
  namespace: kube-system
