apiVersion: apps/v1
kind: Deployment
metadata:
  name: ama-metrics-ksm
  namespace: kube-system
  labels:
    app.kubernetes.io/component: ama-metrics
    app.kubernetes.io/name: ama-metrics-ksm
    app.kubernetes.io/part-of: ama-metrics-ksm
    app.kubernetes.io/version: 2.6.0
    helm.sh/chart: azure-monitor-metrics-addon-0.1.0
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ama-metrics-ksm
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/component: ama-metrics
        app.kubernetes.io/name: ama-metrics-ksm
        app.kubernetes.io/part-of: ama-metrics-ksm
        app.kubernetes.io/version: 2.6.0
        helm.sh/chart: azure-monitor-metrics-addon-0.1.0
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      hostNetwork: false
      serviceAccountName: ama-metrics-ksm
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsUser: 65534
      containers:
      - name: ama-metrics-ksm
        env:
          - name: AZMON_COLLECT_ENV
            value: "false"
        args:
        - --port=8080
        {{- if .Values.AzureMonitorMetrics }}
          {{- if .Values.AzureMonitorMetrics.KubeStateMetrics }}
            {{-  if .Values.AzureMonitorMetrics.KubeStateMetrics.Collectors }}
        - --resources={{ .Values.AzureMonitorMetrics.KubeStateMetrics.Collectors | join "," }}
            {{-  end  }}
          {{-  end  }}
        {{-  end  }}
        {{- if .Values.AzureMonitorMetrics }}
          {{- if .Values.AzureMonitorMetrics.KubeStateMetrics }}
            {{- if .Values.AzureMonitorMetrics.KubeStateMetrics.MetricLabelsAllowlist }}
        - --metric-labels-allowlist={{ .Values.AzureMonitorMetrics.KubeStateMetrics.MetricLabelsAllowlist | join "," }}
            {{- end }}
          {{- end }}
        {{- end }}
        {{- if .Values.AzureMonitorMetrics }}
          {{- if .Values.AzureMonitorMetrics.KubeStateMetrics }}
            {{- if .Values.AzureMonitorMetrics.KubeStateMetrics.MetricAnnotationsAllowList }}
        - --metric-annotations-allowlist={{ .Values.AzureMonitorMetrics.KubeStateMetrics.MetricAnnotationsAllowList | join "," }}
            {{- end }}
          {{- end }}
        {{- end }}
        - --telemetry-port=8081
        imagePullPolicy: IfNotPresent
        {{- if .Values.AzureMonitorMetrics }}
          {{- if .Values.AzureMonitorMetrics.KubeStateMetrics }}
        image: "mcr.microsoft.com{{ .Values.AzureMonitorMetrics.KubeStateMetrics.ImageRepository }}:{{ .Values.AzureMonitorMetrics.KubeStateMetrics.ImageTag }}"
          {{-  end  }}
        {{-  end  }}
        resources:
          limits:
            cpu: 1
            memory: 5Gi
          requests:
            cpu: 5m
            memory: 50Mi
        ports:
        - containerPort: 8080
          name: "http"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        nodeAffinity:
          # affinity to schedule on to ephemeral os node if its available
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: kubernetes.azure.com/mode
                operator: In
                values:
                - system
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-kubelet
                  - key: kubernetes.azure.com/cluster
                    operator: Exists
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - operator: "Exists"
          effect: NoExecute
        - operator: "Exists"
          effect: NoSchedule
