{{- if .Values.AzureMonitorMetrics.OperatorTargetsHttpsEnabled }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace "ama-metrics-operator-targets-client-tls-secret" }}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: ama-metrics-operator-targets-client-tls-secret
  namespace: kube-system
type: Opaque
data:
{{- end }}
{{- end }}

