apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ama-metrics-kube-system-secrets-rolebinding
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: ama-metrics-serviceaccount
    namespace: kube-system
roleRef:
  kind: Role
  name: ama-metrics-kube-system-secrets
  apiGroup: rbac.authorization.k8s.io
