apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: memory-leak
  name: memory-leak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-leak
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: memory-leak
    spec:
      volumes:
        - name: html
          emptyDir: {}
      containers:
        - name: memoryleak-1
          image: valentinomiazzo/jvm-memory-test
          resources:
            limits:
              cpu: 150m
              memory: 15Mi
            requests:
              cpu: 75m
              memory: 12Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext: {}
      schedulerName: default-scheduler
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Equal
          value: 'true'
          effect: NoSchedule
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600