{
 "title": "My Weather Service",
 "tags": [ "weatherapp(custom)" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(myapp_temperature, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature in pnw cities (GAUGE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "myapp_temperature" }
   ]
  },
  {
   "title": "Rate of measurements taken per city (COUNTER)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (city) (rate(myapp_measurements_total{cluster=\"$cluster\"}[2m]))"
    }
   ]
  },
  {
   "title": "90th percentile [0.9 quantile] temperature by city (HISTOGRAM)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(myapp_temperature_histogram_bucket{location=\"pnw\", cluster=\"$cluster\"}[2m]))"
    }
   ]
  },
  {
   "title": "AVG Temperature by city [SUMMARY]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(myapp_temperature_summary_sum{cluster=\"$cluster\"}[2m])\r\n/\r\nrate(myapp_temperature_summary_count{cluster=\"$cluster\"}[2m])"
    }
   ]
  },
  {
   "title": "Python Client Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "python_gc_objects_collected_total"
    }
   ]
  },
  {
   "title": "Untyped Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    { "expr": "untyped_metric" }
   ]
  }
 ]
}