apiVersion: azmonitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: prom_pqs_prod
spec:
  selector:
    matchLabels:
      environment: (?i)prod
    matchExpressions:
      - key: app
        operator: In
        values: [promwebapi-queryworker, promwebapi-queryfrontend, promwebapi-queryservice, nginx-ingress]
    namespaceSelector:
      matchNames: [promwebapi-queryworker, promwebapi-queryfrontend, promwebapi-queryservice]
  podTargetLabels: [app, region, environment, cluster, region]
  podMetricsEndpoints:
    - relabelings:
      - targetLabel: microsoft_metrics_account
        action: replace
        replacement: "pamw-cloudgbl-bl-p"
---
apiVersion: azmonitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: obs-istiod-prod
spec:
  namespaceSelector:
    matchNames:
      - istio-system
  endpoints:
    - port: http-monitoring
      relabelings:
        - sourceLabels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
          action: keep
          regex: istiod
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: citadel_server_root_cert_expiry_timestamp|endpoint_no_pod|istio_build|pilot_endpoint_not_ready|pilot_services|sidecar_injection_requests_total|sidecar_injection_success_total
          action: keep

---
