{
 "title": "CPU and Memory utilization k-s-m, replicaset and daemonset",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "cluster = ci-prod-arc-wcus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replicaset CPU %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "(sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-prod-arc-wcus\", namespace=\"kube-system\", container!=\"\", pod=~\"ama-metrics.*\"}) - sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-prod-arc-wcus\", namespace=\"kube-system\", pod=~\"ama-metrics-node.*\"}) - sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-prod-arc-wcus\", namespace=\"kube-system\", pod=~\"ama-metrics-ksm.*\"}))/ sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"ci-prod-arc-wcus\", namespace=\"kube-system\", resource=\"cpu\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Replicaset CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-prod-arc-wcus\", namespace=\"kube-system\", container!=\"\", pod=~\"ama-metrics.*\"}) - sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-prod-arc-wcus\", namespace=\"kube-system\", pod=~\"ama-metrics-node.*\"}) - sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-prod-arc-wcus\", namespace=\"kube-system\", pod=~\"ama-metrics-ksm.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Daemonset CPU%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-prod-arc-wcus\", namespace=\"kube-system\", container!=\"\", pod=~\"ama-metrics-node.*\"})  / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"ci-prod-arc-wcus\", namespace=\"kube-system\", resource=\"cpu\"}) "
      }
     ]
    },
    {
     "title": "Daemonset CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-prod-arc-wcus\", namespace=\"kube-system\", container!=\"\", pod=~\"ama-metrics-node.*\"})  "
      }
     ]
    },
    {
     "title": "K-S-M CPU%",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-prod-arc-wcus\", namespace=\"kube-system\", container!=\"\", pod=~\"ama-metrics-ksm.*\"})/ sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"ci-prod-arc-wcus\", namespace=\"kube-system\", resource=\"cpu\"})"
      }
     ]
    },
    {
     "title": "K-S-M CPU",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-prod-arc-wcus\", namespace=\"kube-system\", container!=\"\", pod=~\"ama-metrics-ksm.*\"})"
      }
     ]
    },
    {
     "title": "K-S-M Memory%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-prod-arc-wcus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-ksm.*\"}) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"ci-prod-arc-wcus\", namespace=\"kube-system\", resource=\"memory\"})"
      }
     ]
    },
    {
     "title": "K-S-M Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-prod-arc-wcus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-ksm.*\"}) "
      }
     ]
    },
    {
     "title": "Daemonset Memory%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-prod-arc-wcus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-node.*\"}) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"ci-prod-arc-wcus\", namespace=\"kube-system\", resource=\"memory\"})"
      }
     ]
    },
    {
     "title": "Daemonset Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-prod-arc-wcus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-node.*\"})"
      }
     ]
    },
    {
     "title": "Replicaset Memory%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "(sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-prod-arc-wcus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics.*\"}) - sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-prod-arc-wcus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-node.*\"}) - sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-prod-arc-wcus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-ksm.*\"})) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"ci-prod-arc-wcus\", namespace=\"kube-system\", resource=\"memory\"})"
      }
     ]
    },
    {
     "title": "Replicaset Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "expr": "(sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-prod-arc-wcus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics.*\"}) - sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-prod-arc-wcus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-node.*\"}) - sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-prod-arc-wcus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-ksm.*\"})) "
      }
     ]
    },
    {
     "title": "up metric missing for target = kube-dns in cluster ci-prod-arc-wcus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": " up{cluster=\"ci-prod-arc-wcus\", job=\"kube-dns\"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = cadvisor in cluster ci-prod-arc-wcus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "targets": [
      {
       "expr": "absent(up{cluster=\"ci-prod-arc-wcus\", job=\"cadvisor\"}) == 1 or  up{cluster=\"ci-prod-arc-wcus\", job=\"cadvisor\"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = kube-state-metrics in cluster ci-prod-arc-wcus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "absent(up{cluster=\"ci-prod-arc-wcus\", job=\"kube-state-metrics\"}) == 1 or  up{cluster=\"ci-prod-arc-wcus\", job=\"kube-state-metrics\"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = kube-proxy-windows in cluster ci-prod-arc-wcus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "targets": [
      {
       "expr": " up{cluster=\"ci-prod-arc-wcus\", job=\"kube-proxy-windows\"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = kube-apiserver in cluster ci-prod-arc-wcus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": " up{cluster=\"ci-prod-arc-wcus\", job=\"kube-apiserver\"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = kube-proxy in cluster ci-prod-arc-wcus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "targets": [
      {
       "expr": " up{cluster=\"ci-prod-arc-wcus\", job=\"kube-proxy\"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = windows-exporter in cluster ci-prod-arc-wcus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "targets": [
      {
       "expr": " up{cluster=\"ci-prod-arc-wcus\", job=\"windows-exporter\"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = kubelet in cluster ci-prod-arc-wcus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "targets": [
      {
       "expr": " up{cluster=\"ci-prod-arc-wcus\", job=\"kubelet \"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = node in cluster ci-prod-arc-wcus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "targets": [
      {
       "expr": "absent(up{cluster=\"ci-prod-arc-wcus\", job=\"node\"}) == 1 or  up{cluster=\"ci-prod-arc-wcus\", job=\"node\"} == 0"
      }
     ]
    },
    {
     "title": "Aarch64 metric missing ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "targets": [
      {
       "expr": "absent(node_uname_info{cluster=\"ci-prod-arc-wcus\", machine=\"aarch64\"}) == 1 or node_uname_info{cluster=\"ci-prod-arc-wcus\", machine=\"aarch64\"} == 0\r\n\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Amd64 metric missing",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "targets": [
      {
       "expr": "absent(node_uname_info{cluster=\"ci-prod-arc-wcus\", machine=\"x86_64\"}) == 1 or node_uname_info{cluster=\"ci-prod-arc-wcus\", machine=\"x86_64\"} == 0\r\n\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Firing alerts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "targets": [
      {
       "expr": "count (alerts{alertstate=\"firing\"}) by (alertname, cluster)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster = ci-dev-arc-wcus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replicaset CPU %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "(sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-dev-arc-wcus\", namespace=\"kube-system\", container!=\"\", pod=~\"ama-metrics.*\"}) - sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-dev-arc-wcus\", namespace=\"kube-system\", pod=~\"ama-metrics-node.*\"}) - sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-dev-arc-wcus\", namespace=\"kube-system\", pod=~\"ama-metrics-ksm.*\"}))/ sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"ci-dev-arc-wcus\", namespace=\"kube-system\", resource=\"cpu\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Replicaset CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-dev-arc-wcus\", namespace=\"kube-system\", container!=\"\", pod=~\"ama-metrics.*\"}) - sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-dev-arc-wcus\", namespace=\"kube-system\", pod=~\"ama-metrics-node.*\"}) - sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-dev-arc-wcus\", namespace=\"kube-system\", pod=~\"ama-metrics-ksm.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Daemonset CPU%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-dev-arc-wcus\", namespace=\"kube-system\", container!=\"\", pod=~\"ama-metrics-node.*\"})  / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"ci-dev-arc-wcus\", namespace=\"kube-system\", resource=\"cpu\"}) "
      }
     ]
    },
    {
     "title": "Daemonset CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-dev-arc-wcus\", namespace=\"kube-system\", container!=\"\", pod=~\"ama-metrics-node.*\"})  "
      }
     ]
    },
    {
     "title": "K-S-M CPU%",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-dev-arc-wcus\", namespace=\"kube-system\", container!=\"\", pod=~\"ama-metrics-ksm.*\"})/ sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"ci-dev-arc-wcus\", namespace=\"kube-system\", resource=\"cpu\"})"
      }
     ]
    },
    {
     "title": "K-S-M CPU",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-dev-arc-wcus\", namespace=\"kube-system\", container!=\"\", pod=~\"ama-metrics-ksm.*\"})"
      }
     ]
    },
    {
     "title": "K-S-M Memory%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-dev-arc-wcus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-ksm.*\"}) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"ci-dev-arc-wcus\", namespace=\"kube-system\", resource=\"memory\"})"
      }
     ]
    },
    {
     "title": "K-S-M Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-dev-arc-wcus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-ksm.*\"}) "
      }
     ]
    },
    {
     "title": "Daemonset Memory%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-dev-arc-wcus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-node.*\"}) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"ci-dev-arc-wcus\", namespace=\"kube-system\", resource=\"memory\"})"
      }
     ]
    },
    {
     "title": "Daemonset Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-dev-arc-wcus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-node.*\"})"
      }
     ]
    },
    {
     "title": "Replicaset Memory%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "(sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-dev-arc-wcus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics.*\"}) - sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-dev-arc-wcus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-node.*\"}) - sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-dev-arc-wcus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-ksm.*\"})) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"ci-dev-arc-wcus\", namespace=\"kube-system\", resource=\"memory\"})"
      }
     ]
    },
    {
     "title": "Replicaset Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "(sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-dev-arc-wcus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics.*\"}) - sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-dev-arc-wcus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-node.*\"}) - sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-dev-arc-wcus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-ksm.*\"})) "
      }
     ]
    },
    {
     "title": "up metric missing for target = kube-dns in cluster ci-dev-arc-wcus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": " up{cluster=\"ci-dev-arc-wcus\", job=\"kube-dns\"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = cadvisor in cluster ci-dev-arc-wcus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "targets": [
      {
       "expr": "absent(up{cluster=\"ci-dev-arc-wcus\", job=\"cadvisor\"}) == 1 or  up{cluster=\"ci-dev-arc-wcus\", job=\"cadvisor\"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = kube-state-metrics in cluster ci-dev-arc-wcus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "absent(up{cluster=\"ci-dev-arc-wcus\", job=\"kube-state-metrics\"}) == 1 or  up{cluster=\"ci-dev-arc-wcus\", job=\"kube-state-metrics\"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = kube-proxy-windows in cluster ci-dev-arc-wcus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "targets": [
      {
       "expr": " up{cluster=\"ci-dev-arc-wcus\", job=\"kube-proxy-windows\"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = kube-apiserver in cluster ci-dev-arc-wcus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": " up{cluster=\"ci-dev-arc-wcus\", job=\"kube-apiserver\"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = kube-proxy in cluster ci-dev-arc-wcus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "targets": [
      {
       "expr": " up{cluster=\"ci-dev-arc-wcus\", job=\"kube-proxy\"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = windows-exporter in cluster ci-dev-arc-wcus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": " up{cluster=\"ci-dev-arc-wcus\", job=\"windows-exporter\"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = kubelet in cluster ci-dev-arc-wcus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "targets": [
      {
       "expr": " up{cluster=\"ci-dev-arc-wcus\", job=\"kubelet \"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = node in cluster ci-dev-arc-wcus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "targets": [
      {
       "expr": "absent(up{cluster=\"ci-dev-arc-wcus\", job=\"node\"}) == 1 or  up{cluster=\"ci-dev-arc-wcus\", job=\"node\"} == 0"
      }
     ]
    },
    {
     "title": "Aarch64 metric missing ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "targets": [
      {
       "expr": "absent(node_uname_info{cluster=\"ci-dev-arc-wcus\", machine=\"aarch64\"}) == 1 or node_uname_info{cluster=\"ci-dev-arc-wcus\", machine=\"aarch64\"} == 0\r\n\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Amd64 metric missing",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "targets": [
      {
       "expr": "absent(node_uname_info{cluster=\"ci-dev-arc-wcus\", machine=\"x86_64\"}) == 1 or node_uname_info{cluster=\"ci-dev-arc-wcus\", machine=\"x86_64\"} == 0\r\n\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Firing alerts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "targets": [
      {
       "expr": "count (alerts{alertstate=\"firing\"}) by (alertname, cluster)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster = ci-prod-aks-mac-weu",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replicaset CPU %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "(sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-prod-aks-mac-weu\", namespace=\"kube-system\", container!=\"\", pod=~\"ama-metrics.*\"}) - sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-prod-aks-mac-weu\", namespace=\"kube-system\", pod=~\"ama-metrics-node.*\"}) - sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-prod-aks-mac-weu\", namespace=\"kube-system\", pod=~\"ama-metrics-ksm.*\"}))/ sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"ci-prod-aks-mac-weu\", namespace=\"kube-system\", resource=\"cpu\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Replicaset CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-prod-aks-mac-weu\", namespace=\"kube-system\", container!=\"\", pod=~\"ama-metrics.*\"}) - sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-prod-aks-mac-weu\", namespace=\"kube-system\", pod=~\"ama-metrics-node.*\"}) - sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-prod-aks-mac-weu\", namespace=\"kube-system\", pod=~\"ama-metrics-ksm.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Daemonset CPU%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-prod-aks-mac-weu\", namespace=\"kube-system\", container!=\"\", pod=~\"ama-metrics-node.*\"})  / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"ci-prod-aks-mac-weu\", namespace=\"kube-system\", resource=\"cpu\"}) "
      }
     ]
    },
    {
     "title": "Daemonset CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-prod-aks-mac-weu\", namespace=\"kube-system\", container!=\"\", pod=~\"ama-metrics-node.*\"})  "
      }
     ]
    },
    {
     "title": "K-S-M CPU%",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-prod-aks-mac-weu\", namespace=\"kube-system\", container!=\"\", pod=~\"ama-metrics-ksm.*\"})/ sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"ci-prod-aks-mac-weu\", namespace=\"kube-system\", resource=\"cpu\"})"
      }
     ]
    },
    {
     "title": "K-S-M CPU",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-prod-aks-mac-weu\", namespace=\"kube-system\", container!=\"\", pod=~\"ama-metrics-ksm.*\"})"
      }
     ]
    },
    {
     "title": "K-S-M Memory%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-prod-aks-mac-weu\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-ksm.*\"}) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"ci-prod-aks-mac-weu\", namespace=\"kube-system\", resource=\"memory\"})"
      }
     ]
    },
    {
     "title": "K-S-M Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-prod-aks-mac-weu\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-ksm.*\"}) "
      }
     ]
    },
    {
     "title": "Daemonset Memory%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-prod-aks-mac-weu\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-node.*\"}) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"ci-prod-aks-mac-weu\", namespace=\"kube-system\", resource=\"memory\"})"
      }
     ]
    },
    {
     "title": "Daemonset Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-prod-aks-mac-weu\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-node.*\"})"
      }
     ]
    },
    {
     "title": "Replicaset Memory%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "(sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-prod-aks-mac-weu\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics.*\"}) - sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-prod-aks-mac-weu\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-node.*\"}) - sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-prod-aks-mac-weu\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-ksm.*\"})) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"ci-prod-aks-mac-weu\", namespace=\"kube-system\", resource=\"memory\"})"
      }
     ]
    },
    {
     "title": "Replicaset Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "(sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-prod-aks-mac-weu\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics.*\"}) - sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-prod-aks-mac-weu\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-node.*\"}) - sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-prod-aks-mac-weu\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-ksm.*\"})) "
      }
     ]
    },
    {
     "title": "up metric missing for target = kube-dns in cluster ci-prod-aks-mac-weu",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": " up{cluster=\"ci-prod-aks-mac-weu\", job=\"kube-dns\"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = cadvisor in cluster ci-prod-aks-mac-weu",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "targets": [
      {
       "expr": "absent(up{cluster=\"ci-prod-aks-mac-weu\", job=\"cadvisor\"}) == 1 or  up{cluster=\"ci-prod-aks-mac-weu\", job=\"cadvisor\"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = kube-state-metrics in cluster ci-prod-aks-mac-weu",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "absent(up{cluster=\"ci-prod-aks-mac-weu\", job=\"kube-state-metrics\"}) == 1 or  up{cluster=\"ci-prod-aks-mac-weu\", job=\"kube-state-metrics\"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = kube-proxy-windows in cluster ci-prod-aks-mac-weu",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "targets": [
      {
       "expr": " up{cluster=\"ci-prod-aks-mac-weu\", job=\"kube-proxy-windows\"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = kube-apiserver in cluster ci-prod-aks-mac-weu",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": " up{cluster=\"ci-prod-aks-mac-weu\", job=\"kube-apiserver\"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = kube-proxy in cluster ci-prod-aks-mac-weu",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "targets": [
      {
       "expr": " up{cluster=\"ci-prod-aks-mac-weu\", job=\"kube-proxy\"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = windows-exporter in cluster ci-prod-aks-mac-weu",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": " up{cluster=\"ci-prod-aks-mac-weu\", job=\"windows-exporter\"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = kubelet in cluster ci-prod-aks-mac-weu",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "targets": [
      {
       "expr": " up{cluster=\"ci-prod-aks-mac-weu\", job=\"kubelet \"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = node in cluster ci-prod-aks-mac-weu",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "absent(up{cluster=\"ci-prod-aks-mac-weu\", job=\"node\"}) == 1 or  up{cluster=\"ci-prod-aks-mac-weu\", job=\"node\"} == 0"
      }
     ]
    },
    {
     "title": "Aarch64 metric missing ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "targets": [
      {
       "expr": "absent(node_uname_info{cluster=\"ci-prod-aks-mac-weu\", machine=\"aarch64\"}) == 1 or node_uname_info{cluster=\"ci-prod-aks-mac-weu\", machine=\"aarch64\"} == 0\r\n\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Amd64 metric missing",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "targets": [
      {
       "expr": "absent(node_uname_info{cluster=\"ci-prod-aks-mac-weu\", machine=\"x86_64\"}) == 1 or node_uname_info{cluster=\"ci-prod-aks-mac-weu\", machine=\"x86_64\"} == 0\r\n\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Firing alerts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
     "targets": [
      {
       "expr": "count (alerts{alertstate=\"firing\"}) by (alertname, cluster)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster = ci-dev-aks-mac-eus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replicaset CPU %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "(sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-dev-aks-mac-eus\", namespace=\"kube-system\", container!=\"\", pod=~\"ama-metrics.*\"}) - sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-dev-aks-mac-eus\", namespace=\"kube-system\", pod=~\"ama-metrics-node.*\"}) - sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-dev-aks-mac-eus\", namespace=\"kube-system\", pod=~\"ama-metrics-ksm.*\"}))/ sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"ci-dev-aks-mac-eus\", namespace=\"kube-system\", resource=\"cpu\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Replicaset CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-dev-aks-mac-eus\", namespace=\"kube-system\", container!=\"\", pod=~\"ama-metrics.*\"}) - sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-dev-aks-mac-eus\", namespace=\"kube-system\", pod=~\"ama-metrics-node.*\"}) - sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-dev-aks-mac-eus\", namespace=\"kube-system\", pod=~\"ama-metrics-ksm.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Daemonset CPU%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-dev-aks-mac-eus\", namespace=\"kube-system\", container!=\"\", pod=~\"ama-metrics-node.*\"})  / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"ci-dev-aks-mac-eus\", namespace=\"kube-system\", resource=\"cpu\"}) "
      }
     ]
    },
    {
     "title": "Daemonset CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-dev-aks-mac-eus\", namespace=\"kube-system\", container!=\"\", pod=~\"ama-metrics-node.*\"})  "
      }
     ]
    },
    {
     "title": "K-S-M CPU%",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-dev-aks-mac-eus\", namespace=\"kube-system\", container!=\"\", pod=~\"ama-metrics-ksm.*\"})/ sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"ci-dev-aks-mac-eus\", namespace=\"kube-system\", resource=\"cpu\"})"
      }
     ]
    },
    {
     "title": "K-S-M CPU",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "sum ( node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"ci-dev-aks-mac-eus\", namespace=\"kube-system\", container!=\"\", pod=~\"ama-metrics-ksm.*\"})"
      }
     ]
    },
    {
     "title": "K-S-M Memory%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-dev-aks-mac-eus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-ksm.*\"}) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"ci-dev-aks-mac-eus\", namespace=\"kube-system\", resource=\"memory\"})"
      }
     ]
    },
    {
     "title": "K-S-M Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-dev-aks-mac-eus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-ksm.*\"}) "
      }
     ]
    },
    {
     "title": "Daemonset Memory%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-dev-aks-mac-eus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-node.*\"}) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"ci-dev-aks-mac-eus\", namespace=\"kube-system\", resource=\"memory\"})"
      }
     ]
    },
    {
     "title": "Daemonset Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-dev-aks-mac-eus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-node.*\"})"
      }
     ]
    },
    {
     "title": "Replicaset Memory%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "(sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-dev-aks-mac-eus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics.*\"}) - sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-dev-aks-mac-eus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-node.*\"}) - sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-dev-aks-mac-eus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-ksm.*\"})) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"ci-dev-aks-mac-eus\", namespace=\"kube-system\", resource=\"memory\"})"
      }
     ]
    },
    {
     "title": "Replicaset Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "(sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-dev-aks-mac-eus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics.*\"}) - sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-dev-aks-mac-eus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-node.*\"}) - sum(container_memory_working_set_bytes{job=\"cadvisor\", cluster=\"ci-dev-aks-mac-eus\", namespace=\"kube-system\",container!=\"\", image!=\"\", pod=~\"ama-metrics-ksm.*\"})) "
      }
     ]
    },
    {
     "title": "up metric missing for target = kube-dns in cluster ci-dev-aks-mac-eus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": " up{cluster=\"ci-dev-aks-mac-eus\", job=\"kube-dns\"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = cadvisor in cluster ci-dev-aks-mac-eus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "targets": [
      {
       "expr": "absent(up{cluster=\"ci-dev-aks-mac-eus\", job=\"cadvisor\"}) == 1 or  up{cluster=\"ci-dev-aks-mac-eus\", job=\"cadvisor\"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = kube-state-metrics in cluster ci-dev-aks-mac-eus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "absent(up{cluster=\"ci-dev-aks-mac-eus\", job=\"kube-state-metrics\"}) == 1 or  up{cluster=\"ci-dev-aks-mac-eus\", job=\"kube-state-metrics\"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = kube-proxy-windows in cluster ci-dev-aks-mac-eus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "targets": [
      {
       "expr": " up{cluster=\"ci-dev-aks-mac-eus\", job=\"kube-proxy-windows\"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = kube-apiserver in cluster ci-prod-aks-mac-weu",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "targets": [
      {
       "expr": " up{cluster=\"ci-dev-aks-mac-eus\", job=\"kube-apiserver\"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = kube-proxy in cluster ci-dev-aks-mac-eus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "targets": [
      {
       "expr": " up{cluster=\"ci-dev-aks-mac-eus\", job=\"kube-proxy\"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = windows-exporter in cluster ci-dev-aks-mac-eus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "targets": [
      {
       "expr": " up{cluster=\"ci-dev-aks-mac-eus\", job=\"windows-exporter\"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = kubelet in cluster ci-dev-aks-mac-eus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "targets": [
      {
       "expr": " up{cluster=\"ci-dev-aks-mac-eus\", job=\"kubelet \"} == 0"
      }
     ]
    },
    {
     "title": "up metric missing for target = node in cluster ci-dev-aks-mac-eus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "targets": [
      {
       "expr": "absent(up{cluster=\"ci-dev-aks-mac-eus\", job=\"node\"}) == 1 or  up{cluster=\"ci-dev-aks-mac-eus\", job=\"node\"} == 0"
      }
     ]
    },
    {
     "title": "Aarch64 metric missing ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "targets": [
      {
       "expr": "absent(node_uname_info{cluster=\"ci-dev-aks-mac-eus\", machine=\"aarch64\"}) == 1 or node_uname_info{cluster=\"ci-dev-aks-mac-eus\", machine=\"aarch64\"} == 0\r\n\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Amd64 metric missing",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "targets": [
      {
       "expr": "absent(node_uname_info{cluster=\"ci-dev-aks-mac-eus\", machine=\"x86_64\"}) == 1 or node_uname_info{cluster=\"ci-dev-aks-mac-eus\", machine=\"x86_64\"} == 0\r\n\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Firing alerts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
     "targets": [
      {
       "expr": "count (alerts{alertstate=\"firing\"}) by (alertname, cluster)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}