apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-prometheus-collector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-collector.labels" . | nindent 4 }}