kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "prometheus-collector.fullname" . }}-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: {{ template "prometheus-collector.fullname" . }}-serviceaccount
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "prometheus-collector.fullname" . }}-reader
  apiGroup: rbac.authorization.k8s.io
