apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-collector.fullname" . }}-serviceaccount
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-collector.labels" . | nindent 4 }}