apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-collector.fullname" . }}-serviceaccount
  {{- if not .Values.useMonitoringAccount }}
  namespace: {{ .Release.Namespace }}
  {{- else }}
  namespace: kube-system
  {{- end }}
  labels:
    {{- include "prometheus-collector.labels" . | nindent 4 }}