kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-prometheus-collector-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-prometheus-collector
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-prometheus-collector-reader
  apiGroup: rbac.authorization.k8s.io
