kind: ConfigMap
apiVersion: v1
data:
  schema-version:
    #string.used by agent to parse config. supported versions are {v1}. Configs with other schema versions will be rejected by the agent.
    v1
  config-version:
    #string.used by customer to keep track of this config file's version in their source control/repository (max allowed 10 chars, other chars will be truncated)
    ver1
  prometheus-collector-settings: |-
  {{- if not .Values.useMonitoringAccount }}
    default_metric_account_name = {{ required "azureMetricAccount.defaultAccountName is required" .Values.azureMetricAccount.defaultAccountName | toString | quote }}
  {{- else }}
    default_metric_account_name = "notapplicable"
  {{- end }}
    cluster_alias = {{ index .Values "clusterAlias" | toString | quote }}
  default-scrape-settings-enabled: |-
    kubelet = {{ .Values.scrapeTargets.kubelet }}
    coredns = {{ .Values.scrapeTargets.coreDns }}
    cadvisor = {{ .Values.scrapeTargets.cAdvisor }}
    kubeproxy = {{ .Values.scrapeTargets.kubeProxy }}
    apiserver = {{ .Values.scrapeTargets.apiServer }}
    kubestate = {{ .Values.scrapeTargets.kubeState }}
    nodeexporter = {{ .Values.scrapeTargets.nodeExporter }}
    prometheuscollectorhealth = {{ .Values.scrapeTargets.prometheusCollectorHealth }}
    windowsexporter = {{ .Values.scrapeTargets.windowsExporter }}
    windowskubeproxy = {{ .Values.scrapeTargets.windowsKubeProxy }}
  default-targets-metrics-keep-list: |-
    kubelet = {{ .Values.keepListRegexes.kubelet | toString | quote }}
    coredns = {{ .Values.keepListRegexes.coreDns | toString | quote }}
    cadvisor = {{ .Values.keepListRegexes.cAdvisor | toString | quote }}
    kubeproxy = {{ .Values.keepListRegexes.kubeProxy | toString | quote }}
    apiserver = {{ .Values.keepListRegexes.apiServer | toString | quote }}
    kubestate = {{ .Values.keepListRegexes.kubeState | toString | quote }}
    nodeexporter = {{ .Values.keepListRegexes.nodeExporter | toString | quote }}
    windowsexporter = {{ .Values.keepListRegexes.windowsExporter | toString | quote }}
    windowskubeproxy = {{ .Values.keepListRegexes.windowsKubeProxy | toString | quote }}
  debug-mode: |-
    enabled = {{ .Values.debugMode.enabled }}
  default-targets-scrape-interval-settings: |-
    kubelet = {{ .Values.scrapeIntervalTargets.kubelet | toString | quote}}
    coredns = {{ .Values.scrapeIntervalTargets.coreDns | toString | quote}}
    cadvisor = {{ .Values.scrapeIntervalTargets.cAdvisor | toString | quote}}
    kubeproxy = {{ .Values.scrapeIntervalTargets.kubeProxy | toString | quote}}
    apiserver = {{ .Values.scrapeIntervalTargets.apiServer | toString | quote}}
    kubestate = {{ .Values.scrapeIntervalTargets.kubeState | toString | quote}}
    nodeexporter = {{ .Values.scrapeIntervalTargets.nodeExporter | toString | quote}}
    prometheuscollectorhealth = {{ .Values.scrapeIntervalTargets.prometheusCollectorHealth | toString | quote}}
    windowsexporter = {{ .Values.scrapeIntervalTargets.windowsExporter | toString | quote}}
    windowskubeproxy = {{ .Values.scrapeIntervalTargets.windowsKubeProxy | toString | quote}}
metadata:
  name: {{ template "prometheus-collector.fullname" . }}-settings-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-collector.labels" . | nindent 4 }}
