# Source: ama-metrics-cpp/templates/ama-metrics-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ama-metrics-ccp-role
  namespace: {{ .Values.global.commonGlobals.Customer.Namespace }}
rules:
  - apiGroups: [""]
    resources:
      [
        "pods",
        "endpoints",
      ]
    verbs: ["list", "get", "watch"]
---
# Source: ama-metrics-cpp/templates/ama-metrics-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ama-metrics-ccp-role
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["aad-msi-auth-token"]
    verbs: ["get", "watch"]