kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ama-metrics-ccp-rolebinding
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: ama-metrics-ccp-sa
    namespace: {{ .Values.global.commonGlobals.Customer.Namespace }}
roleRef:
  kind: Role
  name:  ama-metrics-ccp-role
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ama-metrics-ccp-rolebinding
  namespace: {{ .Values.global.commonGlobals.Customer.Namespace }}
subjects:
  - kind: ServiceAccount
    name: ama-metrics-ccp-sa
    namespace: {{ .Values.global.commonGlobals.Customer.Namespace }}
roleRef:
  kind: Role
  name:  ama-metrics-ccp-role
  apiGroup: rbac.authorization.k8s.io
