apiVersion: v1
kind: Secret
metadata:
  name: monitor-auth
  namespace: ama-metrics-auth-telemetry-test
type: Opaque
stringData:
  username: telemetry-user
  password: telemetry-password
  bearer-token: telemetry-bearer-token
