{
 "title": "Kubernetes / USE Method / Node(Windows) (RR)",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(windows_system_system_up_time, cluster)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(windows_system_system_up_time{cluster=\"$cluster\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": " 1 - avg by (instance) (\n                rate(windows_cpu_time_total{cluster=\"$cluster\",job=\"windows-exporter\",mode=\"idle\",instance=\"$instance\"}[1m]))",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "CPU Usage Per Core",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (core) (irate(windows_cpu_time_total{cluster=\"$cluster\", job=\"windows-exporter\",mode!=\"idle\", instance=\"$instance\"}[5m]))",
     "legendFormat": "{{core}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory Utilisation %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - ((windows_memory_available_bytes{cluster=\"$cluster\",job=\"windows-exporter\",instance=\"$instance\"}) / windows_os_visible_memory_bytes{cluster=\"$cluster\",job=\"windows-exporter\",instance=\"$instance\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(\n  windows_os_visible_memory_bytes{job=\"windows-exporter\", instance=\"$instance\", cluster=\"$cluster\"}\n  - windows_memory_available_bytes{job=\"windows-exporter\", instance=\"$instance\", cluster=\"$cluster\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "max((windows_memory_cache_bytes{job=\"windows-exporter\", cluster=\"$cluster\",instance=\"$instance\"} + windows_memory_modified_page_list_bytes{job=\"windows-exporter\", cluster=\"$cluster\",instance=\"$instance\"} + windows_memory_standby_cache_core_bytes{job=\"windows-exporter\", cluster=\"$cluster\",instance=\"$instance\"} + windows_memory_standby_cache_normal_priority_bytes{job=\"windows-exporter\", cluster=\"$cluster\",instance=\"$instance\"} + windows_memory_standby_cache_reserve_bytes{job=\"windows-exporter\", cluster=\"$cluster\",instance=\"$instance\"}))",
     "legendFormat": "memory cached"
    },
    {
     "expr": "max(windows_memory_available_bytes{job=\"windows-exporter\", cluster=\"$cluster\", instance=\"$instance\"})",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory Saturation (Swap I/O) Pages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(windows_memory_swap_page_operations_total{cluster=\"$cluster\", job=\"windows-exporter\", instance=\"$instance\"}[5m])",
     "legendFormat": "Swap IO"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Disk IO Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (\n                (irate(windows_logical_disk_read_seconds_total{cluster=\"$cluster\", job=\"windows-exporter\", instance=\"$instance\"}[1m]) +\n                 irate(windows_logical_disk_write_seconds_total{cluster=\"$cluster\", job=\"windows-exporter\", instance=\"$instance\"}[1m]))\n              )",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(rate(windows_logical_disk_read_bytes_total{job=\"windows-exporter\", cluster=\"$cluster\",instance=\"$instance\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "expr": "max(rate(windows_logical_disk_write_bytes_total{job=\"windows-exporter\", cluster=\"$cluster\",instance=\"$instance\"}[2m]))",
     "legendFormat": "written"
    },
    {
     "expr": "max(rate(windows_logical_disk_read_seconds_total{job=\"windows-exporter\", cluster=\"$cluster\",  instance=\"$instance\"}[2m]) + rate(windows_logical_disk_write_seconds_total{job=\"windows-exporter\", cluster=\"$cluster\", instance=\"$instance\"}[2m]))",
     "legendFormat": "io time"
    }
   ]
  },
  { "title": "Net", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Net Utilisation (Transmitted)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (\n                (irate(windows_net_bytes_total{job=\"windows-exporter\", cluster=\"$cluster\", instance=\"$instance\"}[1m]))\n              )",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Net Saturation (Dropped)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (\n                (irate(windows_net_packets_received_discarded_total{cluster=\"$cluster\", job=\"windows-exporter\", instance=\"$instance\"}[1m]) +\n                irate(windows_net_packets_outbound_discarded_total{cluster=\"$cluster\", job=\"windows-exporter\", instance=\"$instance\"}[1m]))\n              )",
     "legendFormat": "Saturation"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Disk Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": " max by (instance,volume)(\n                (windows_logical_disk_size_bytes{cluster=\"$cluster\", job=\"windows-exporter\", instance=\"$instance\"}\n              - windows_logical_disk_free_bytes{cluster=\"$cluster\", job=\"windows-exporter\", instance=\"$instance\"})\n              / windows_logical_disk_size_bytes{cluster=\"$cluster\", job=\"windows-exporter\", instance=\"$instance\"}\n              )\n",
     "legendFormat": "{{volume}}"
    }
   ]
  }
 ]
}