scrape_configs:
  - job_name: prometheus_ref_app
    scheme: http
    scrape_interval: 60s
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_app]
      action: keep
      regex: "prometheus-reference-app"
