apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-reference-app-2
spec:
  selector:
    matchLabels:
      app: prometheus-reference-app-2
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-reference-app-2
    spec:
      containers:
        - name: prometheus-reference-app-golang-2
          resources:
            requests:
              cpu: 2
              memory: 2Gi
          image: gracepromacr.azurecr.io/prometheus-reference-app:golang-061822-1
          env:
            - name: RUN_PERF_TEST
              value: "true"
            - name: SCRAPE_INTERVAL
              value: "15"
            - name: METRIC_COUNT
              value: "31250"
          ports:
            - containerPort: 2112
              protocol: TCP
            - containerPort: 2113
              protocol: TCP
        - name: prometheus-reference-app-python-2
          image: gracepromacr.azurecr.io/prometheus-reference-app:python-082521
          ports:
          - containerPort: 2114
            protocol: TCP
      nodeSelector:
          kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-reference-service-2
spec:
  selector:
    app: prometheus-reference-app-2
  ports:
    - name: "weather-app"
      protocol: TCP
      port: 2112
      targetPort: 2112
    - name: "untyped-metrics"
      protocol: TCP
      port: 2113
      targetPort: 2113
    - name: "python-client"
      protocol: TCP
      port: 2114
      targetPort: 2114
