scrape_configs:
  - job_name: win_prometheus_ref_app
    scrape_interval: 60s
    scheme: http
    metrics_path: /metrics
    static_configs:
    - targets: ['win-prometheus-reference-service.default.svc.cluster.local:2112','win-prometheus-reference-service.default.svc.cluster.local:2113','win-prometheus-reference-service.default.svc.cluster.local:2114']
