{
 "title": "Kubernetes / Compute Resources / Workload",
 "description": "Source-https://github.com/monitoring-mixins/website/blob/master/assets/kubernetes/dashboards/k8s-resources-workload.json",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "type",
    "query": {
     "query": "label_values(kube_pod_owner{cluster=~\"$cluster\",namespace=~\"$namespace\"}, owner_kind)"
    }
   },
   {
    "name": "workload",
    "query": {
     "query": "label_values(kube_pod_owner{cluster=~\"$cluster\",namespace=~\"$namespace\",owner_kind=\"$type\"}, owner_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\r\n    sum by (cluster, namespace, pod, container) (\r\n          rate(container_cpu_usage_seconds_total{job=~\"cadvisor\", image!=\"\", container!=\"POD\",cluster=~\"$cluster\", namespace=~\"$namespace\"}[5m])\r\n        ) * on (cluster, namespace, pod) group_left(node) topk by (cluster, namespace, pod) (\r\n          1, max by(cluster, namespace, pod, node) (kube_pod_info)\r\n        )\r\n  * on(namespace,pod)\r\n    group_left(owner_name, owner_kind) kube_pod_owner{cluster=~\"$cluster\", namespace=~\"$namespace\", owner_name=~\"$workload\", owner_kind=~\"$type\"}\r\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Quota",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\r\n    sum by (cluster, namespace, pod, container) (\r\n          rate(container_cpu_usage_seconds_total{job=~\"cadvisor\", image!=\"\", container!=\"POD\",cluster=~\"$cluster\", namespace=~\"$namespace\"}[5m])\r\n        ) * on (cluster, namespace, pod) group_left(node) topk by (cluster, namespace, pod) (\r\n          1, max by(cluster, namespace, pod, node) (kube_pod_info)\r\n        )\r\n  * on(namespace,pod)\r\n    group_left(owner_name, owner_kind) kube_pod_owner{cluster=~\"$cluster\", namespace=\"$namespace\", owner_name=~\"$workload\", owner_kind=\"$type\"}\r\n) by (pod)\n"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(owner_name, owner_kind) kube_pod_owner{cluster=~\"$cluster\", namespace=\"$namespace\", owner_name=~\"$workload\", owner_kind=\"$type\"}\n) by (pod)\n"
      },
      {
       "expr": "sum(\n    sum by (cluster, namespace, pod, container) (\r\n          rate(container_cpu_usage_seconds_total{job=~\"cadvisor\", image!=\"\", container!=\"POD\",cluster=~\"$cluster\", namespace=~\"$namespace\"}[5m])\r\n        ) * on (cluster, namespace, pod) group_left(node) topk by (cluster, namespace, pod) (\r\n          1, max by(cluster, namespace, pod, node) (kube_pod_info)\r\n        )\n  * on(namespace,pod)\n    group_left(owner_name, owner_kind) kube_pod_owner{cluster=~\"$cluster\", namespace=\"$namespace\", owner_name=~\"$workload\", owner_kind=\"$type\"}\n) by (pod)\n/sum(\n    kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(owner_name, owner_kind) kube_pod_owner{cluster=~\"$cluster\", namespace=\"$namespace\", owner_name=~\"$workload\", owner_kind=\"$type\"}\n) by (pod)\n"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(owner_name, owner_kind) kube_pod_owner{cluster=~\"$cluster\", namespace=\"$namespace\", owner_name=~\"$workload\", owner_kind=\"$type\"}\n) by (pod)\n"
      },
      {
       "expr": "sum(\n    sum by (cluster, namespace, pod, container) (\r\n          rate(container_cpu_usage_seconds_total{job=~\"cadvisor\", image!=\"\", container!=\"POD\",cluster=~\"$cluster\", namespace=~\"$namespace\"}[5m])\r\n        ) * on (cluster, namespace, pod) group_left(node) topk by (cluster, namespace, pod) (\r\n          1, max by(cluster, namespace, pod, node) (kube_pod_info)\r\n        )\n  * on(namespace,pod)\n    group_left(owner_name, owner_kind) kube_pod_owner{cluster=~\"$cluster\", namespace=\"$namespace\", owner_name=~\"$workload\", owner_kind=\"$type\"}\n) by (pod)\n/sum(\n    kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(owner_name, owner_kind) kube_pod_owner{cluster=~\"$cluster\", namespace=\"$namespace\",owner_name=~\"$workload\", owner_kind=\"$type\"}\n) by (pod)\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(\n    container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=\"$namespace\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(owner_name, owner_kind) kube_pod_owner{cluster=~\"$cluster\", namespace=\"$namespace\", owner_name=~\"$workload\", owner_kind=\"$type\"}\n) by (pod)\n",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Quota",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n    container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=\"$namespace\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(owner_name, owner_kind) kube_pod_owner{cluster=~\"$cluster\", namespace=\"$namespace\", owner_name=~\"$workload\", owner_kind=\"$type\"}\n) by (pod)\n"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=\"$namespace\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(owner_name, owner_kind) kube_pod_owner{cluster=~\"$cluster\", namespace=\"$namespace\", owner_name=~\"$workload\", owner_kind=\"$type\"}\n) by (pod)\n"
      },
      {
       "expr": "sum(\n    container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=\"$namespace\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(owner_name, owner_kind) kube_pod_owner{cluster=~\"$cluster\", namespace=\"$namespace\", owner_name=~\"$workload\", owner_kind=\"$type\"}\n) by (pod)\n/sum(\n    kube_pod_container_resource_requests{cluster=~\"$cluster\", namespace=\"$namespace\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(owner_name, owner_kind) kube_pod_owner{cluster=~\"$cluster\", namespace=\"$namespace\", owner_name=~\"$workload\", owner_kind=\"$type\"}\n) by (pod)\n"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=\"$namespace\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(owner_name, owner_kind) kube_pod_owner{cluster=~\"$cluster\", namespace=\"$namespace\", owner_name=~\"$workload\", owner_kind=\"$type\"}\n) by (pod)\n"
      },
      {
       "expr": "sum(\n    container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=\"$namespace\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(owner_name, owner_kind) kube_pod_owner{cluster=~\"$cluster\", namespace=\"$namespace\", owner_name=~\"$workload\", owner_kind=\"$type\"}\n) by (pod)\n/sum(\n    kube_pod_container_resource_limits{cluster=~\"$cluster\", namespace=\"$namespace\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(owner_name, owner_kind) kube_pod_owner{cluster=~\"$cluster\", namespace=\"$namespace\", owner_name=~\"$workload\", owner_kind=\"$type\"}\n) by (pod)\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Current Network Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Network Usage",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(sum(irate(container_network_receive_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(owner_name,owner_kind) kube_pod_owner{cluster=~\"$cluster\", namespace=~\"$namespace\", owner_name=~\"$workload\", owner_kind=\"$type\"}) by (pod))\n"
      },
      {
       "expr": "(sum(irate(container_network_transmit_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(owner_name,owner_kind) kube_pod_owner{cluster=~\"$cluster\", namespace=~\"$namespace\", owner_name=~\"$workload\", owner_kind=\"$type\"}) by (pod))\n"
      },
      {
       "expr": "(sum(irate(container_network_receive_packets_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(owner_name,owner_kind) kube_pod_owner{cluster=~\"$cluster\", namespace=~\"$namespace\", owner_name=~\"$workload\", owner_kind=\"$type\"}) by (pod))\n"
      },
      {
       "expr": "(sum(irate(container_network_transmit_packets_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(owner_name,owner_kind) kube_pod_owner{cluster=~\"$cluster\", namespace=~\"$namespace\", owner_name=~\"$workload\", owner_kind=\"$type\"}) by (pod))\n"
      },
      {
       "expr": "(sum(irate(container_network_receive_packets_dropped_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(owner_name,owner_kind) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", owner_name=~\"$workload\", owner_kind=\"$type\"}) by (pod))\n"
      },
      {
       "expr": "(sum(irate(container_network_transmit_packets_dropped_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(owner_name,owner_kind) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\", namespace=~\"$namespace\", owner_name=~\"$workload\", owner_kind=\"$type\"}) by (pod))\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receive Bandwidth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(container_network_receive_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(owner_name,owner_kind) kube_pod_owner{cluster=~\"$cluster\", namespace=~\"$namespace\", owner_name=~\"$workload\", owner_kind=\"$type\"}) by (pod))\n",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(container_network_transmit_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(owner_name,owner_kind) kube_pod_owner{cluster=~\"$cluster\", namespace=~\"$namespace\", owner_name=~\"$workload\", owner_kind=\"$type\"}) by (pod))\n",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Average Container Bandwidth by Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Container Bandwidth by Pod: Received",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(avg(irate(container_network_receive_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(owner_name,owner_kind) kube_pod_owner{cluster=~\"$cluster\", namespace=~\"$namespace\", owner_name=~\"$workload\", owner_kind=\"$type\"}) by (pod))\n",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Average Container Bandwidth by Pod: Transmitted",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(avg(irate(container_network_transmit_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(owner_name,owner_kind) kube_pod_owner{cluster=~\"$cluster\", namespace=~\"$namespace\", owner_name=~\"$workload\", owner_kind=\"$type\"}) by (pod))\n",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rate of Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate of Received Packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(container_network_receive_packets_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(owner_name,owner_kind) kube_pod_owner{cluster=~\"$cluster\", namespace=~\"$namespace\", owner_name=~\"$workload\", owner_kind=\"$type\"}) by (pod))\n",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Transmitted Packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(container_network_transmit_packets_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(owner_name,owner_kind) kube_pod_owner{cluster=~\"$cluster\", namespace=~\"$namespace\", owner_name=~\"$workload\", owner_kind=\"$type\"}) by (pod))\n",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rate of Packets Dropped",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate of Received Packets Dropped",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(container_network_receive_packets_dropped_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(owner_name,owner_kind) kube_pod_owner{cluster=~\"$cluster\", namespace=~\"$namespace\", owner_name=~\"$workload\", owner_kind=\"$type\"}) by (pod))\n",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Transmitted Packets Dropped",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(container_network_transmit_packets_dropped_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(owner_name,owner_kind) kube_pod_owner{cluster=~\"$cluster\", namespace=~\"$namespace\", owner_name=~\"$workload\", owner_kind=\"$type\"}) by (pod))\n",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}