{
 "title": "Kubernetes / Networking / Cluster",
 "description": "Source-https://github.com/monitoring-mixins/website/blob/master/assets/kubernetes/dashboards/cluster-total.json",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "resolution", "query": "30s,5m,1h" },
   { "name": "interval", "query": "4h" },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"cadvisor\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Current Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Rate of Bytes Received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_receive_bytes_total{cluster=~\"$cluster\",namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Current Rate of Bytes Transmitted",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_transmit_bytes_total{cluster=~\"$cluster\",namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Current Status",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_network_receive_bytes_total{cluster=~\"$cluster\",namespace=~\".+\"}[$interval:$resolution])) by (namespace))"
    },
    {
     "expr": "sort_desc(sum(irate(container_network_transmit_bytes_total{cluster=~\"$cluster\",namespace=~\".+\"}[$interval:$resolution])) by (namespace))"
    },
    {
     "expr": "sort_desc(avg(irate(container_network_receive_bytes_total{cluster=~\"$cluster\",namespace=~\".+\"}[$interval:$resolution])) by (namespace))"
    },
    {
     "expr": "sort_desc(avg(irate(container_network_transmit_bytes_total{cluster=~\"$cluster\",namespace=~\".+\"}[$interval:$resolution])) by (namespace))"
    },
    {
     "expr": "sort_desc(sum(irate(container_network_receive_packets_total{cluster=~\"$cluster\",namespace=~\".+\"}[$interval:$resolution])) by (namespace))"
    },
    {
     "expr": "sort_desc(sum(irate(container_network_transmit_packets_total{cluster=~\"$cluster\",namespace=~\".+\"}[$interval:$resolution])) by (namespace))"
    },
    {
     "expr": "sort_desc(sum(irate(container_network_receive_packets_dropped_total{cluster=~\"$cluster\",namespace=~\".+\"}[$interval:$resolution])) by (namespace))"
    },
    {
     "expr": "sort_desc(sum(irate(container_network_transmit_packets_dropped_total{cluster=~\"$cluster\",namespace=~\".+\"}[$interval:$resolution])) by (namespace))"
    }
   ]
  },
  {
   "title": "Average Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Rate of Bytes Received",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sort_desc(avg(irate(container_network_receive_bytes_total{cluster=~\"$cluster\",namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Average Rate of Bytes Transmitted",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sort_desc(avg(irate(container_network_transmit_bytes_total{cluster=~\"$cluster\",namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bandwidth History",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receive Bandwidth",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(irate(container_network_receive_bytes_total{cluster=~\"$cluster\",namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(irate(container_network_transmit_bytes_total{cluster=~\"$cluster\",namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate of Received Packets",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(irate(container_network_receive_packets_total{cluster=~\"$cluster\",namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Rate of Transmitted Packets",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(irate(container_network_transmit_packets_total{cluster=~\"$cluster\",namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate of Received Packets Dropped",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(irate(container_network_receive_packets_dropped_total{cluster=~\"$cluster\",namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Rate of Transmitted Packets Dropped",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(irate(container_network_transmit_packets_dropped_total{cluster=~\"$cluster\",namespace=~\".+\"}[$interval:$resolution])) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Rate of TCP Retransmits out of all sent segments",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(rate(node_netstat_Tcp_RetransSegs{cluster=~\"$cluster\"}[$interval:$resolution]) / rate(node_netstat_Tcp_OutSegs{cluster=~\"$cluster\"}[$interval:$resolution])) by (instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Rate of TCP SYN Retransmits out of all retransmits",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(rate(node_netstat_TcpExt_TCPSynRetrans{cluster=~\"$cluster\"}[$interval:$resolution]) / rate(node_netstat_Tcp_RetransSegs{cluster=~\"$cluster\"}[$interval:$resolution])) by (instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}