{
 "title": "Kubernetes / Compute Resources / Namespace (Workloads)",
 "description": "Source-https://github.com/monitoring-mixins/website/blob/master/assets/kubernetes/dashboards/k8s-resources-workloads-namespace.json",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "type",
    "query": {
     "query": "label_values(kube_pod_owner{cluster=\"$cluster\",namespace=\"$namespace\"}, owner_kind)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n   sum by (cluster, namespace, pod, container) (\r\n          rate(container_cpu_usage_seconds_total{job=\"cadvisor\", image!=\"\", container!=\"POD\",cluster=\"$cluster\", namespace=\"$namespace\"}[5m])\r\n        ) * on (cluster, namespace, pod) group_left(node) topk by (cluster, namespace, pod) (\r\n          1, max by(cluster, namespace, pod, node) (kube_pod_info)\r\n        )\n* on(namespace,pod)\n  group_left(owner_name, owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_kind=\"$type\"}\n) by (owner_name, owner_kind)\n",
     "legendFormat": "{{owner_name}} - {{owner_kind}}"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", type=\"hard\",resource=\"requests.cpu\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", type=\"hard\",resource=\"limits.cpu\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  { "title": "CPU Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_kind=\"$type\"}) by (owner_name, owner_kind)"
    },
    {
     "expr": "sum(\n   sum by (cluster, namespace, pod, container) (\r\n          rate(container_cpu_usage_seconds_total{job=\"cadvisor\", image!=\"\", container!=\"POD\",cluster=\"$cluster\", namespace=\"$namespace\"}[5m])\r\n        ) * on (cluster, namespace, pod) group_left(node) topk by (cluster, namespace, pod) (\r\n          1, max by(cluster, namespace, pod, node) (kube_pod_info)\r\n        )\n* on(namespace,pod)\n  group_left(owner_name, owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_kind=\"$type\"}\n) by (owner_name, owner_kind)\n"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", resource=\"cpu\"}\n* on(namespace,pod)\n  group_left(owner_name, owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_kind=\"$type\"}\n) by (owner_name, owner_kind)\n"
    },
    {
     "expr": "sum(\n   sum by (cluster, namespace, pod, container) (\r\n          rate(container_cpu_usage_seconds_total{job=\"cadvisor\", image!=\"\", container!=\"POD\",cluster=\"$cluster\", namespace=\"$namespace\"}[5m])\r\n        ) * on (cluster, namespace, pod) group_left(node) topk by (cluster, namespace, pod) (\r\n          1, max by(cluster, namespace, pod, node) (kube_pod_info)\r\n        )\n* on(namespace,pod)\n  group_left(owner_name, owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_kind=\"$type\"}\n) by (owner_name, owner_kind)\n/sum(\n  kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", resource=\"cpu\"}\n* on(namespace,pod)\n  group_left(owner_name, owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_kind=\"$type\"}\n) by (owner_name, owner_kind)\n"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", resource=\"cpu\"}\n* on(namespace,pod)\n  group_left(owner_name, owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_kind=\"$type\"}\n) by (owner_name, owner_kind)\n"
    },
    {
     "expr": "sum(\n   sum by (cluster, namespace, pod, container) (\r\n          rate(container_cpu_usage_seconds_total{job=\"cadvisor\", image!=\"\", container!=\"POD\",cluster=\"$cluster\", namespace=\"$namespace\"}[5m])\r\n        ) * on (cluster, namespace, pod) group_left(node) topk by (cluster, namespace, pod) (\r\n          1, max by(cluster, namespace, pod, node) (kube_pod_info)\r\n        )\n* on(namespace,pod)\n  group_left(owner_name, owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_kind=\"$type\"}\n) by (owner_name, owner_kind)\n/sum(\n  kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", resource=\"cpu\"}\n* on(namespace,pod)\n  group_left(owner_name, owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_kind=\"$type\"}\n) by (owner_name, owner_kind)\n"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(owner_name, owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_kind=\"$type\"}\n) by (owner_name, owner_kind)\n",
     "legendFormat": "{{owner_name}} - {{owner_kind}}"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", type=\"hard\",resource=\"requests.memory\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{cluster=\"$cluster\", namespace=\"$namespace\", type=\"hard\",resource=\"limits.memory\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  { "title": "Memory Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload_type=\"$type\"}) by (workload, workload_type)"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(owner_name, owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_Kind=\"$type\"}\n) by (owner_name, owner_kind)\n"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", resource=\"memory\"}\n* on(namespace,pod)\n  group_left(owner_name, owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_kind=\"$type\"}\n) by (owner_name, owner_kind)\n"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(owner_name, owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_kind=\"$type\"}\n) by (owner_name, owner_kind)\n/sum(\n  kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", resource=\"memory\"}\n* on(namespace,pod)\n  group_left(owner_name, owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_kind=\"$type\"}\n) by (owner_name, owner_kind)\n"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", resource=\"memory\"}\n* on(namespace,pod)\n  group_left(owner_name, owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_kind=\"$type\"}\n) by (owner_name, owner_kind)\n"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(owner_name, owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_kind=\"$type\"}\n) by (owner_name, owner_kind)\n/sum(\n  kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", resource=\"memory\"}\n* on(namespace,pod)\n  group_left(owner_name, owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_kind=\"$type\"}\n) by (owner_name, owner_kind)\n"
    }
   ]
  },
  { "title": "Current Network Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Current Network Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(owner_name,owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_kind=\"$type\"}) by (owner_name))\n"
    },
    {
     "expr": "(sum(irate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(owner_name,owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_kind=\"$type\"}) by (owner_name))\n"
    },
    {
     "expr": "(sum(irate(container_network_receive_packets_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(owner_name,owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_kind=\"$type\"}) by (owner_name))\n"
    },
    {
     "expr": "(sum(irate(container_network_transmit_packets_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(owner_name,owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_kind=\"$type\"}) by (owner_name))\n"
    },
    {
     "expr": "(sum(irate(container_network_receive_packets_dropped_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(owner_name,owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_kind=\"$type\"}) by (owner_name))\n"
    },
    {
     "expr": "(sum(irate(container_network_transmit_packets_dropped_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(owner_name,owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_kind=\"$type\"}) by (owner_name))\n"
    }
   ]
  },
  { "title": "Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(owner_name,owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_name=~\".+\", owner_kind=\"$type\"}) by (owner_name))\n",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(owner_name,owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_name=~\".+\", owner_kind=\"$type\"}) by (owner_name))\n",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Average Container Bandwidth by Workload",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 }
  },
  {
   "title": "Average Container Bandwidth by Workload: Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(avg(irate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(owner_name,owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_name=~\".+\", owner_kind=\"$type\"}) by (owner_name))\n",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Average Container Bandwidth by Workload: Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(avg(irate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(owner_name,owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_name=~\".+\", owner_kind=\"$type\"}) by (owner_name))\n",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  { "title": "Rate of Packets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Rate of Received Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_packets_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(owner_name,owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_name=~\".+\", owner_kind=\"$type\"}) by (owner_name))\n",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(container_network_transmit_packets_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(owner_name,owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_name=~\".+\", owner_kind=\"$type\"}) by (owner_name))\n",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  { "title": "Rate of Packets Dropped", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_packets_dropped_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(owner_name,owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_name=~\".+\", owner_kind=\"$type\"}) by (owner_name))\n",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(container_network_transmit_packets_dropped_total{cluster=\"$cluster\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(owner_name,owner_kind) kube_pod_owner{cluster=\"$cluster\", namespace=\"$namespace\", owner_name=~\".+\", owner_kind=\"$type\"}) by (owner_name))\n",
     "legendFormat": "{{workload}}"
    }
   ]
  }
 ]
}