{
 "title": "Kubernetes / Compute Resources / Node (Pods)",
 "description": "Source-https://github.com/monitoring-mixins/website/blob/master/assets/kubernetes/dashboards/k8s-resources-node.json",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info{cluster=~\"$cluster\"}, node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum by (cluster, namespace, pod, container) (\r\n                rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", instance=~\"$node\", image!=\"\"}[5m])\r\n              ) * on (cluster, namespace, pod) group_left(node) topk by (cluster, namespace, pod) (\r\n                1, max by(cluster, namespace, pod, node) (kube_pod_info{node!=\"\"})\r\n              )) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "CPU Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Quota",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum by (cluster, namespace, pod, container) (\r\n          rate(container_cpu_usage_seconds_total{job=\"cadvisor\", image!=\"\", cluster=~\"$cluster\", instance=~\"$node\"}[5m])\r\n        ) * on (cluster, namespace, pod) group_left(node) topk by (cluster, namespace, pod) (\r\n          1, max by(cluster, namespace, pod, node) (kube_pod_info{cluster=~\"$cluster\", node=~\"$node\"})\r\n        )) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\", node=~\"$node\", resource=\"cpu\"}) by (pod)"
    },
    {
     "expr": "sum(sum by (cluster, namespace, pod, container) (\r\n          rate(container_cpu_usage_seconds_total{job=\"cadvisor\", image!=\"\", cluster=~\"$cluster\", instance=~\"$node\"}[5m])\r\n        ) * on (cluster, namespace, pod) group_left(node) topk by (cluster, namespace, pod) (\r\n          1, max by(cluster, namespace, pod, node) (kube_pod_info{node!=\"\"})\r\n        )) by (pod) / sum(kube_pod_container_resource_requests{cluster=~\"$cluster\", node=~\"$node\", resource=\"cpu\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\", node=~\"$node\", resource=\"cpu\"}) by (pod)"
    },
    {
     "expr": "sum(sum by (cluster, namespace, pod, container) (\r\n          rate(container_cpu_usage_seconds_total{job=\"cadvisor\", image!=\"\", cluster=~\"$cluster\", instance=~\"$node\"}[5m])\r\n        ) * on (cluster, namespace, pod) group_left(node) topk by (cluster, namespace, pod) (\r\n          1, max by(cluster, namespace, pod, node) (kube_pod_info{node!=\"\"})\r\n        )) by (pod) / sum(kube_pod_container_resource_limits{cluster=~\"$cluster\", node=~\"$node\", resource=\"cpu\"}) by (pod)"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum( container_memory_working_set_bytes{cluster=~\"$cluster\", instance=~\"$node\", container!=\"\", image!=\"\"}\r\n              * on (namespace, pod) group_left(node) topk by(namespace, pod) (1,\r\n                max by(namespace, pod, node) (kube_pod_info{node!=\"\"})\r\n              )     ) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Memory Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Memory Quota",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"cadvisor\", image!=\"\", cluster=~\"$cluster\", instance=~\"$node\",container!=\"\"}\r\n        * on (namespace, pod) group_left(node) topk by(namespace, pod) (1,\r\n          max by(namespace, pod, node) (kube_pod_info{node!=\"\"})\r\n        )) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\", node=~\"$node\", resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"cadvisor\", image!=\"\", instance=~\"$node\", cluster=~\"$cluster\"}\r\n        * on (namespace, pod) group_left(node) topk by(namespace, pod) (1,\r\n          max by(namespace, pod, node) (kube_pod_info{node!=\"\"})\r\n        )) by (pod) / sum(kube_pod_container_resource_requests{cluster=~\"$cluster\", node=~\"$node\", resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\", node=~\"$node\", resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"cadvisor\", image!=\"\", instance=~\"$node\", cluster=~\"$cluster\"}\r\n        * on (namespace, pod) group_left(node) topk by(namespace, pod) (1,\r\n          max by(namespace, pod, node) (kube_pod_info{node!=\"\", cluster=~\"$cluster\"})\r\n        )) by (pod) / sum(kube_pod_container_resource_limits{cluster=~\"$cluster\", node=~\"$node\", resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_rss{job=\"cadvisor\", image!=\"\", instance=~\"$node\", cluster=~\"$cluster\"}\r\n        * on (namespace, pod) group_left(node) topk by(namespace, pod) (1,\r\n          max by(namespace, pod, node) (kube_pod_info{node!=\"\", cluster=~\"$cluster\"})\r\n        )) by (pod)"
    },
    {
     "expr": "sum(container_memory_cache{job=\"cadvisor\", image!=\"\", instance=~\"$node\", cluster=~\"$cluster\"}\r\n        * on (namespace, pod) group_left(node) topk by(namespace, pod) (1,\r\n          max by(namespace, pod, node) (kube_pod_info{node!=\"\", cluster=~\"$cluster\"})\r\n        )) by (pod)"
    },
    {
     "expr": "sum(container_memory_swap{job=\"cadvisor\", image!=\"\", instance=~\"$node\", cluster=~\"$cluster\"}\r\n        * on (namespace, pod) group_left(node) topk by(namespace, pod) (1,\r\n          max by(namespace, pod, node) (kube_pod_info{node!=\"\", cluster=~\"$cluster\"})\r\n        )) by (pod)"
    }
   ]
  }
 ]
}