exporters:
  prometheus:
    endpoint: "127.0.0.1:9091"
    const_labels:
      cluster: ${env:AZMON_CLUSTER_LABEL}
  otlp:
    endpoint: 127.0.0.1:55680
    tls:
      insecure: true
    compression: "gzip"
    retry_on_failure:
      enabled: false
    timeout: 12s
processors:
  batch:
    send_batch_size: 7000
    timeout: 200ms
    send_batch_max_size: 7000
  resource:
    attributes:
    - key: cluster
      value: "${env:AZMON_CLUSTER_LABEL}"
      action: "upsert"
    - key: job
      from_attribute: service.name
      action: insert
    - key: instance
      from_attribute: service.instance.id
      action: insert
receivers:
    prometheus:
      config:
service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [otlp]
      processors: [batch, resource]
  telemetry:
    logs:
      level: warn
      encoding: json
      output_paths: ["collector.log.json"]
    metrics:
      level: detailed
