# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - id: configmap-watcher
    binary: configmap-watcher
    ldflags:
      - -X 'go.goms.io/aks/configmap-watcher.Version={{.Version}}'
      - -X 'go.goms.io/aks/configmap-watcher.Commit={{.Commit}}'
      - -X 'go.goms.io/aks/configmap-watcher.Date={{.Date}}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
archives:
  - name_template: 'configmap-watcher-{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    #format: binary
    #wrap_in_directory: true
    files:
      - config/**/*
      - deploy/**/*
      - hack/deploy/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-{{.ShortCommit}}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
