AzureMonitorMetrics:
  ImageRepository: mcr.microsoft.com${MCR_REPOSITORY}
  ImageTag: ${IMAGE_TAG}
  # The below 2 settings are not Azure Monitor Metrics adapter chart. They are substituted in a different manner.
  # Please update these with the latest ones from here so that you get the image that is currently deployed by the AKS RP -
  # Repository: https://msazure.visualstudio.com/CloudNativeCompute/_git/aks-rp?path=/ccp/charts/addon-charts/azure-monitor-metrics-addon/templates/ama-metrics-daemonset.yaml&version=GBrashmi/prom-addon-arm64&line=136&lineEnd=136&lineStartColumn=56&lineEndColumn=85&lineStyle=plain&_a=contents
  # ImageTag: https://msazure.visualstudio.com/CloudNativeCompute/_git/aks-rp?path=/ccp/charts/kube-control-plane/templates/_images.tpl&version=GBrashmi/prom-addon-arm64&line=530&lineEnd=530&lineStartColumn=28&lineEndColumn=53&lineStyle=plain&_a=contents
  ArcExtension: false
  # Do not change the below settings. They are reserved for Arc Autonomous
  isArcACluster: false
global:
  commonGlobals:
    CloudEnvironment: "azurepubliccloud"
    Region: "${AKS_REGION}"
    Customer:
      AzureResourceID: ${AKS_RESOURCE_ID}
      Namespace: ${AKS_NAMESPACE}
      SubscriptionId: ${SUBSCRIPTION_ID} #msi-adapter
      ResourceGroupName: ${RESOURCE_GROUP} #msi-adapter
      ManagedClusterName: ${AKS_CLUSTER_NAME} #msi-adapter
prometheus-node-exporter:
  service:
    port: 9110
    targetPort: 9110
