macro(DEFINE_OPTION option_name description default_value)
    set(temp_value ${default_value})
    if(FLB_MINIMAL)
        set(temp_value OFF)
    endif()
    option(${option_name} "${description}" ${temp_value})
endmacro()

# Add the FLB_MINIMAL option
option(FLB_MINIMAL "Enable minimal build configuration" No)

# Inputs (sources, data collectors)
# =================================
DEFINE_OPTION(FLB_IN_BLOB                     "Enable Blob input plugin"                     OFF)
DEFINE_OPTION(FLB_IN_CALYPTIA_FLEET           "Enable Calyptia Fleet input plugin"           OFF)
DEFINE_OPTION(FLB_IN_COLLECTD                 "Enable Collectd input plugin"                 OFF)
DEFINE_OPTION(FLB_IN_CPU                      "Enable CPU input plugin"                      OFF)
DEFINE_OPTION(FLB_IN_DISK                     "Enable Disk input plugin"                     OFF)
DEFINE_OPTION(FLB_IN_DOCKER                   "Enable Docker input plugin"                   OFF)
DEFINE_OPTION(FLB_IN_DOCKER_EVENTS            "Enable Docker events input plugin"            OFF)
DEFINE_OPTION(FLB_IN_DUMMY                    "Enable Dummy input plugin"                    OFF)
DEFINE_OPTION(FLB_IN_ELASTICSEARCH            "Enable Elasticsearch (Bulk API) input plugin" OFF)
# Necessary for rewrite_tag filter plugin
DEFINE_OPTION(FLB_IN_EMITTER                  "Enable emitter input plugin"                  ON)
DEFINE_OPTION(FLB_IN_EVENT_TEST               "Enable event test plugin"                     OFF)
DEFINE_OPTION(FLB_IN_EVENT_TYPE               "Enable event type plugin"                     OFF)
DEFINE_OPTION(FLB_IN_EXEC                     "Enable Exec input plugin"                     OFF)
DEFINE_OPTION(FLB_IN_EXEC_WASI                "Enable Exec WASI input plugin"                OFF)
DEFINE_OPTION(FLB_IN_FLUENTBIT_METRICS        "Enable Fluent Bit metrics plugin"             OFF)
DEFINE_OPTION(FLB_IN_FORWARD                  "Enable Forward input plugin"                  OFF)
DEFINE_OPTION(FLB_IN_HEAD                     "Enable Head input plugin"                     OFF)
DEFINE_OPTION(FLB_IN_HEALTH                   "Enable Health input plugin"                   OFF)
DEFINE_OPTION(FLB_IN_HTTP                     "Enable HTTP input plugin"                     OFF)
DEFINE_OPTION(FLB_IN_KAFKA                    "Enable Kafka input plugin"                    OFF)
DEFINE_OPTION(FLB_IN_KMSG                     "Enable Kernel log input plugin"               OFF)
DEFINE_OPTION(FLB_IN_KUBERNETES_EVENTS        "Enable Kubernetes Events plugin"              OFF)
DEFINE_OPTION(FLB_IN_LIB                      "Enable library mode input plugin"             OFF)
DEFINE_OPTION(FLB_IN_MEM                      "Enable Memory input plugin"                   OFF)
DEFINE_OPTION(FLB_IN_MQTT                     "Enable MQTT Broker input plugin"              OFF)
DEFINE_OPTION(FLB_IN_NETIF                    "Enable NetworkIF input plugin"                OFF)
DEFINE_OPTION(FLB_IN_NGINX_EXPORTER_METRICS   "Enable Nginx Metrics input plugin"            OFF)
DEFINE_OPTION(FLB_IN_NODE_EXPORTER_METRICS    "Enable node exporter metrics input plugin"    OFF)
DEFINE_OPTION(FLB_IN_OPENTELEMETRY            "Enable OpenTelemetry input plugin"            OFF)
DEFINE_OPTION(FLB_IN_PODMAN_METRICS           "Enable Podman Metrics input plugin"           OFF)
DEFINE_OPTION(FLB_IN_PROCESS_EXPORTER_METRICS "Enable process exporter metrics input plugin" OFF)
DEFINE_OPTION(FLB_IN_PROC                     "Enable Process input plugin"                  OFF)
DEFINE_OPTION(FLB_IN_PROMETHEUS_REMOTE_WRITE  "Enable prometheus remote write input plugin"  OFF)
DEFINE_OPTION(FLB_IN_PROMETHEUS_SCRAPE        "Enable Prometheus Scrape input plugin"        OFF)
DEFINE_OPTION(FLB_IN_RANDOM                   "Enable random input plugin"                   OFF)
DEFINE_OPTION(FLB_IN_SERIAL                   "Enable Serial input plugin"                   OFF)
DEFINE_OPTION(FLB_IN_SPLUNK                   "Enable Splunk HTTP HEC input plugin"          OFF)
DEFINE_OPTION(FLB_IN_STATSD                   "Enable StatsD input plugin"                   OFF)
DEFINE_OPTION(FLB_IN_STDIN                    "Enable Standard input plugin"                 OFF)
DEFINE_OPTION(FLB_IN_STORAGE_BACKLOG          "Enable storage backlog input plugin"          OFF)
DEFINE_OPTION(FLB_IN_SYSLOG                   "Enable Syslog input plugin"                   OFF)
DEFINE_OPTION(FLB_IN_SYSTEMD                  "Enable Systemd input plugin"                  OFF)
DEFINE_OPTION(FLB_IN_TAIL                     "Enable Tail input plugin"                     ON)
DEFINE_OPTION(FLB_IN_TCP                      "Enable TCP input plugin"                      OFF)
DEFINE_OPTION(FLB_IN_THERMAL                  "Enable Thermal plugin"                        OFF)
DEFINE_OPTION(FLB_IN_UDP                      "Enable UDP input plugin"                      OFF)
DEFINE_OPTION(FLB_IN_UNIX_SOCKET              "Enable Unix socket input plugin"              OFF)
DEFINE_OPTION(FLB_IN_WINLOG                   "Enable Windows Log input plugin"              OFF)
DEFINE_OPTION(FLB_IN_WINDOWS_EXPORTER_METRICS "Enable windows exporter metrics input plugin" OFF)
DEFINE_OPTION(FLB_IN_WINEVTLOG                "Enable Windows EvtLog input plugin"           OFF)
DEFINE_OPTION(FLB_IN_WINSTAT                  "Enable Windows Stat input plugin"             OFF)
DEFINE_OPTION(FLB_IN_EBPF                     "Enable Linux eBPF input plugin"               OFF)

# Processors
# ==========
DEFINE_OPTION(FLB_PROCESSOR_CONTENT_MODIFIER  "Enable content modifier processor"            OFF)
DEFINE_OPTION(FLB_PROCESSOR_LABELS            "Enable metrics label manipulation processor"  OFF)
DEFINE_OPTION(FLB_PROCESSOR_METRICS_SELECTOR  "Enable metrics selector processor"            OFF)
DEFINE_OPTION(FLB_PROCESSOR_SQL               "Enable SQL processor"                         OFF)
DEFINE_OPTION(FLB_PROCESSOR_OPENTELEMETRY_ENVELOPE "Enable OpenTelemetry envelope processor" OFF)

# Filters
# =======
DEFINE_OPTION(FLB_FILTER_ALTER_SIZE           "Enable alter_size filter"                     OFF)
DEFINE_OPTION(FLB_FILTER_AWS                  "Enable aws filter"                            OFF)
DEFINE_OPTION(FLB_FILTER_CHECKLIST            "Enable checklist filter"                      OFF)
DEFINE_OPTION(FLB_FILTER_ECS                  "Enable AWS ECS filter"                        OFF)
DEFINE_OPTION(FLB_FILTER_EXPECT               "Enable expect filter"                         OFF)
DEFINE_OPTION(FLB_FILTER_GEOIP2               "Enable geoip2 filter"                         OFF)
DEFINE_OPTION(FLB_FILTER_GREP                 "Enable grep filter"                           ON)
DEFINE_OPTION(FLB_FILTER_KUBERNETES           "Enable kubernetes filter"                     OFF)
DEFINE_OPTION(FLB_FILTER_LOG_TO_METRICS       "Enable log-derived metrics filter"            OFF)
DEFINE_OPTION(FLB_FILTER_LUA                  "Enable Lua scripting filter"                  OFF)
DEFINE_OPTION(FLB_FILTER_LUA_USE_MPACK        "Enable mpack on the lua filter"               OFF)
DEFINE_OPTION(FLB_FILTER_MODIFY               "Enable modify filter"                         OFF)
DEFINE_OPTION(FLB_FILTER_MULTILINE            "Enable multiline filter"                      OFF)
DEFINE_OPTION(FLB_FILTER_NEST                 "Enable nest filter"                           OFF)
DEFINE_OPTION(FLB_FILTER_NIGHTFALL            "Enable Nightfall filter"                      OFF)
DEFINE_OPTION(FLB_FILTER_PARSER               "Enable parser filter"                         ON)
DEFINE_OPTION(FLB_FILTER_RECORD_MODIFIER      "Enable record_modifier filter"                OFF)
DEFINE_OPTION(FLB_FILTER_REWRITE_TAG          "Enable tag rewrite filter"                    ON)
DEFINE_OPTION(FLB_FILTER_STDOUT               "Enable stdout filter"                         OFF)
DEFINE_OPTION(FLB_FILTER_SYSINFO              "Enable sysinfo filter"                        OFF)
DEFINE_OPTION(FLB_FILTER_THROTTLE             "Enable throttle filter"                       OFF)
DEFINE_OPTION(FLB_FILTER_THROTTLE_SIZE        "Enable throttle size filter"                  OFF)
DEFINE_OPTION(FLB_FILTER_TYPE_CONVERTER       "Enable type converter filter"                 OFF)
DEFINE_OPTION(FLB_FILTER_TENSORFLOW           "Enable tensorflow filter"                     OFF)
DEFINE_OPTION(FLB_FILTER_WASM                 "Enable WASM filter"                           OFF)

# Outputs (destinations)
# ======================
DEFINE_OPTION(FLB_OUT_AZURE                   "Enable Azure output plugin"                   OFF)
DEFINE_OPTION(FLB_OUT_AZURE_BLOB              "Enable Azure output plugin"                   OFF)
DEFINE_OPTION(FLB_OUT_AZURE_KUSTO             "Enable Azure Kusto output plugin"             OFF)
DEFINE_OPTION(FLB_OUT_AZURE_LOGS_INGESTION    "Enable Azure Logs Ingestion output plugin"    OFF)
DEFINE_OPTION(FLB_OUT_BIGQUERY                "Enable BigQuery output plugin"                OFF)
DEFINE_OPTION(FLB_OUT_CALYPTIA                "Enable Calyptia monitoring plugin"            OFF)
DEFINE_OPTION(FLB_OUT_CHRONICLE               "Enable Google Chronicle output plugin"        OFF)
DEFINE_OPTION(FLB_OUT_CLOUDWATCH_LOGS         "Enable AWS CloudWatch output plugin"          OFF)
DEFINE_OPTION(FLB_OUT_COUNTER                 "Enable Counter output plugin"                 OFF)
DEFINE_OPTION(FLB_OUT_DATADOG                 "Enable DataDog output plugin"                 OFF)
DEFINE_OPTION(FLB_OUT_ES                      "Enable Elasticsearch output plugin"           OFF)
DEFINE_OPTION(FLB_OUT_EXIT                    "Enable Exit output plugin"                    OFF)
DEFINE_OPTION(FLB_OUT_FILE                    "Enable file output plugin"                    OFF)
DEFINE_OPTION(FLB_OUT_FLOWCOUNTER             "Enable flowcount output plugin"               OFF)
DEFINE_OPTION(FLB_OUT_FORWARD                 "Enable Forward output plugin"                 OFF)
DEFINE_OPTION(FLB_OUT_GELF                    "Enable GELF output plugin"                    OFF)
DEFINE_OPTION(FLB_OUT_HTTP                    "Enable HTTP output plugin"                    OFF)
DEFINE_OPTION(FLB_OUT_INFLUXDB                "Enable InfluxDB output plugin"                OFF)
DEFINE_OPTION(FLB_OUT_KAFKA                   "Enable Kafka output plugin"                   OFF)
DEFINE_OPTION(FLB_OUT_KAFKA_REST              "Enable Kafka Rest output plugin"              OFF)
DEFINE_OPTION(FLB_OUT_KINESIS_FIREHOSE        "Enable AWS Firehose output plugin"            OFF)
DEFINE_OPTION(FLB_OUT_KINESIS_STREAMS         "Enable AWS Kinesis output plugin"             OFF)
DEFINE_OPTION(FLB_OUT_LIB                     "Enable library mode output plugin"            OFF)
DEFINE_OPTION(FLB_OUT_LOGDNA                  "Enable LogDNA output plugin"                  OFF)
DEFINE_OPTION(FLB_OUT_LOKI                    "Enable Loki output plugin"                    OFF)
DEFINE_OPTION(FLB_OUT_NATS                    "Enable NATS output plugin"                    OFF)
DEFINE_OPTION(FLB_OUT_NRLOGS                  "Enable New Relic output plugin"               OFF)
DEFINE_OPTION(FLB_OUT_NULL                    "Enable dev null output plugin"                OFF)
DEFINE_OPTION(FLB_OUT_OPENSEARCH              "Enable OpenSearch output plugin"              OFF)
DEFINE_OPTION(FLB_OUT_OPENTELEMETRY           "Enable OpenTelemetry plugin"                  OFF)
DEFINE_OPTION(FLB_OUT_ORACLE_LOG_ANALYTICS    "Enable Oracle Cloud Infrastructure Logging analytics plugin" OFF)
DEFINE_OPTION(FLB_OUT_PGSQL                   "Enable PostgreSQL output plugin"              OFF)
DEFINE_OPTION(FLB_OUT_PLOT                    "Enable Plot output plugin"                    OFF)
DEFINE_OPTION(FLB_OUT_PROMETHEUS_EXPORTER     "Enable Prometheus exporter plugin"            OFF)
DEFINE_OPTION(FLB_OUT_PROMETHEUS_REMOTE_WRITE "Enable Prometheus remote write plugin"        OFF)
DEFINE_OPTION(FLB_OUT_RETRY                   "Enable Retry test output plugin"              OFF)
DEFINE_OPTION(FLB_OUT_S3                      "Enable AWS S3 output plugin"                  OFF)
DEFINE_OPTION(FLB_OUT_SKYWALKING              "Enable Apache SkyWalking output plugin"       OFF)
DEFINE_OPTION(FLB_OUT_SLACK                   "Enable Slack output plugin"                   OFF)
DEFINE_OPTION(FLB_OUT_SPLUNK                  "Enable Splunk output plugin"                  OFF)
DEFINE_OPTION(FLB_OUT_STACKDRIVER             "Enable Stackdriver output plugin"             OFF)
DEFINE_OPTION(FLB_OUT_STDOUT                  "Enable STDOUT output plugin"                  ON)
DEFINE_OPTION(FLB_OUT_SYSLOG                  "Enable Syslog output plugin"                  OFF)
DEFINE_OPTION(FLB_OUT_TD                      "Enable Treasure Data output plugin"           OFF)
DEFINE_OPTION(FLB_OUT_TCP                     "Enable TCP output plugin"                     OFF)
DEFINE_OPTION(FLB_OUT_UDP                     "Enable UDP output plugin"                     OFF)
DEFINE_OPTION(FLB_OUT_VIVO_EXPORTER           "Enable Vivo exporter output plugin"           OFF)
DEFINE_OPTION(FLB_OUT_WEBSOCKET               "Enable Websocket output plugin"               OFF)
