trigger:
- none

pool:
  vmImage: windows-latest

stages:
- stage: Deploy
  jobs:
  - job: DeployJob
    steps:
    - template: azure-template-aksdeploy.yml
      parameters:
        azureSubscription: $(AZURESUBSCRIPTION)
        resourceGroup: $(RESOURCE-GROUP)
        deployParameters: ${env:PARAMETERS}

- stage: Test
  dependsOn: Deploy
  jobs:
  - job: TestJob
    steps:
    - template: azure-template-regionstest.yml
      parameters:
        azureSubscription: $(AZURESUBSCRIPTION)
        resourceGroup: $(RESOURCE-GROUP)
        clusterName: $(CLUSTERNAME)
