trigger:
  branches:
    include:
    - main
pr:
  autoCancel: true
  branches:
    include:
    - main

variables:
  HELM_CHART_NAME: 'prometheus-collector'
  ARC_HELM_CHART_NAME: 'ama-metrics-arc'
  ACR_REGISTRY: 'containerinsightsprod.azurecr.io'
  ACR_REPOSITORY: '/public/azuremonitor/containerinsights/cidev/prometheus-collector/images'
  ACR_REPOSITORY_HELM: '/public/azuremonitor/containerinsights/cidev'
  MCR_REGISTRY: 'mcr.microsoft.com'
  MCR_REPOSITORY: '/azuremonitor/containerinsights/cidev/prometheus-collector/images'
  MCR_REPOSITORY_HELM: '/azuremonitor/containerinsights/cidev/prometheus-collector'
  MCR_REPOSITORY_HELM_DEPENDENCIES: '/azuremonitor/containerinsights/cidev'
  KUBE_STATE_METRICS_IMAGE: 'mcr.microsoft.com/oss/kubernetes/kube-state-metrics:v2.12.0'
  NODE_EXPORTER_IMAGE: 'mcr.microsoft.com/oss/prometheus/node-exporter:v1.8.2'
  IS_PR: $[eq(variables['Build.Reason'], 'PullRequest')]
  IS_MAIN_BRANCH: $[eq(variables['Build.SourceBranchName'], 'main')]
  BUILD_WINDOWS: true
  Codeql.Enabled: true
  GOLANG_VERSION: '1.22.11'
  TESTKUBE_GOLANG_VERSION: '1.23.2'
  FLUENT_BIT_VERSION: '3.2.2'

stages:
- stage: Build
  jobs:
  - job: CreateSidecarArtifact
    displayName: "Create Sidecar YAML Artifact"
    pool:
      vmImage: 'ubuntu-latest'  # Change if using a different agent
    
    steps:
      - task: CopyFiles@2
        displayName: "Copy sidecar.yaml to artifact staging directory"
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)/internal/remotewrite'
          Contents: 'sidecar.yaml'
          TargetFolder: '$(Build.ArtifactStagingDirectory)/drop'

      - task: PublishBuildArtifacts@1
        displayName: "Publish sidecar.yaml as an artifact"
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)/drop'
          artifactName: 'drop'

 