# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: $(AZURESUBSCRIPTION)
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az account show
      az deployment group create `
          --resource-group ${env:RESOURCE-GROUP} `
          --name  ${env:DEPLOYMENT-NAME} `
          --template-file ".\otelcollector\test\ci-cd\ci-cd-cluster.json" `
          --parameters ${env:PARAMETERS}          