trigger:
  branches:
    include:
    - main
  paths:
    include:
    - '*.md'
    - '**/*.md'
    - '.github/*'
    - 'AddonArmTemplate/*'
    - 'AddonBicepTemplate/*'
    - 'AddonPolicyTemplate/*'
    - 'AddonTerraformTemplate/*'
    - 'ArcArmTemplate/*'
    - 'ArcBicepTemplate/*'
    - 'Azure-ARM-templates/*'
    - 'GeneratedMonitoringArtifacts/*'
    - 'internal/alerts/*'
    - 'internal/docs/*'
    - 'internal/monitoring/*'
    - 'internal/scripts/*'
    - 'internal/mixins/*'
    - 'tools/*'

pr:
  autoCancel: true
  branches:
    include:
    - main
  paths:
    include:
    - '*.md'
    - '**/*.md'
    - '.github/*'
    - 'AddonArmTemplate/*'
    - 'AddonBicepTemplate/*'
    - 'AddonPolicyTemplate/*'
    - 'AddonTerraformTemplate/*'
    - 'ArcArmTemplate/*'
    - 'ArcBicepTemplate/*'
    - 'Azure-ARM-templates/*'
    - 'GeneratedMonitoringArtifacts/*'
    - 'internal/alerts/*'
    - 'internal/docs/*'
    - 'internal/monitoring/*'
    - 'internal/scripts/*'
    - 'internal/mixins/*'
    - 'tools/*'
    - '.pipeline/azure-pipeline-build.yml'
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "No build required" '
