scrape_configs:
- job_name: cadvisor
  scheme: https
  metrics_path: /metrics/cadvisor
  scrape_interval: 30s
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  relabel_configs:
  - source_labels: [__address__]
    replacement: '$NODE_NAME'
    target_label: instance
  static_configs:
  - targets: ['$NODE_IP:10250']

- job_name: kubelet
  scheme: https
  metrics_path: /metrics
  scrape_interval: 30s
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  relabel_configs:
  - source_labels: [__metrics_path__]
    regex: (.*)
    target_label: metrics_path
  - source_labels: [__address__]
    replacement: '$NODE_NAME'
    target_label: instance
  static_configs:
  - targets: ['$NODE_IP:10250']

- job_name: node
  scrape_interval: 30s
  scheme: http
  metrics_path: /metrics
  static_configs:
  - targets: ['$NODE_IP:9100']
