kind: ConfigMap
apiVersion: v1
data:
  schema-version:
    v1
  config-version:
    ver1
  prometheus-collector-settings: |-
    default_metric_account_name = "default"
    cluster_alias = ""
  default-scrape-settings-enabled: |-
    kubelet = false
    coredns = false
    cadvisor = false
    kubeproxy = false
    kubestate = false
    apiserver = false
    nodeexporter = false
    prometheuscollectorhealth = false
    windowsexporter = false
    windowskubeproxy = false
    kube-apiserver = false
    cluster-autoscaler = false
    kube-scheduler = false
    kube-controller-manager = false
    etcd = false
  default-targets-metrics-keep-list: |-
    kubelet = ""
    coredns = ""
    cadvisor = ""
    kubeproxy = ""
    kubestate = ""
    nodeexporter = ""
    windowsexporter = ""
    windowskubeproxy = ""
    kube-apiserver = "(.*)"
    cluster-autoscaler = "(.*)"
    kube-scheduler = "(.*)"
    kube-controller-manager = "(.*)"
    etcd = "(.*)"
  debug-mode: |-
    enabled = false
  default-targets-scrape-interval-settings: |-
    kubelet = "30s"
    coredns = "30s"
    cadvisor = "30s"
    kubeproxy = "30s"
    kubestate = "30s"
    nodeexporter = "30s"
    prometheuscollectorhealth = "30s"
    windowsexporter = "30s"
    windowskubeproxy = "30s"
    kube-apiserver = "30s"
    cluster-autoscaler = "30s"
    kube-scheduler = "30s"
    kube-controller-manager = "30s"
    etcd = "30s"
metadata:
  name: ama-metrics-settings-configmap
  namespace: {{ .Values.global.commonGlobals.Customer.Namespace }}