{
 "title": "Kubernetes / USE Method / Cluster(Windows)",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"windows-exporter\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - avg by (instance) (\n                rate(windows_cpu_time_total{cluster=\"$cluster\",job=\"windows-exporter\",mode=\"idle\"}[1m])\n              ) *  count by (instance) (sum by (instance, core) (\n                windows_cpu_time_total{cluster=\"$cluster\",job=\"windows-exporter\"}\n              )) / scalar(sum(count by (instance) (sum by (instance, core) (\n                windows_cpu_time_total{cluster=\"$cluster\",job=\"windows-exporter\"}\n              ))))",
     "legendFormat": "{{instance}}",
     "legendLink": "./d/96e7484b0bb53b74fbc2bcb7723cd40b/k8s-windows-node-rsrc-use"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": " (sum by (instance) (\n                (windows_os_visible_memory_bytes{cluster=\"$cluster\", job=\"windows-exporter\"} or windows_memory_physical_total_bytes{cluster=\"$cluster\", job=\"windows-exporter\"})\n              ) - sum by (instance) (\n                (windows_memory_available_bytes{cluster=\"$cluster\", job=\"windows-exporter\"})\n              ))\n              /\n              scalar(sum(sum by (instance) (\n                (windows_os_visible_memory_bytes{cluster=\"$cluster\", job=\"windows-exporter\"} or windows_memory_physical_total_bytes{cluster=\"$cluster\", job=\"windows-exporter\"})\n              )))",
     "legendFormat": "{{instance}}",
     "legendLink": "./d/96e7484b0bb53b74fbc2bcb7723cd40b/k8s-windows-node-rsrc-use"
    }
   ]
  },
  {
   "title": "Memory Saturation (Swap I/O Pages)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(windows_memory_swap_page_operations_total{cluster=\"$cluster\", job=\"windows-exporter\"}[5m])",
     "legendFormat": "{{instance}}",
     "legendLink": "./d/96e7484b0bb53b74fbc2bcb7723cd40b/k8s-windows-node-rsrc-use"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Disk IO Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": " avg by (instance) (\n                (irate(windows_logical_disk_read_seconds_total{cluster=\"$cluster\", job=\"windows-exporter\"}[1m]) +\n                 irate(windows_logical_disk_write_seconds_total{cluster=\"$cluster\", job=\"windows-exporter\"}[1m]))\n              ) / scalar(count (\n                windows_system_boot_time_timestamp_seconds{cluster=\"$cluster\", job=\"windows-exporter\"} or windows_system_boot_time_timestamp{cluster=\"$cluster\", job=\"windows-exporter\"} or windows_system_system_up_time{cluster=\"$cluster\", job=\"windows-exporter\"}\n              ))",
     "legendFormat": "{{instance}}",
     "legendLink": "./d/96e7484b0bb53b74fbc2bcb7723cd40b/k8s-windows-node-rsrc-use"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Net Utilisation (Transmitted)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (\n                (irate(windows_net_bytes_total{cluster=\"$cluster\", job=\"windows-exporter\"}[1m]))\n              )",
     "legendFormat": "{{instance}}",
     "legendLink": "./d/96e7484b0bb53b74fbc2bcb7723cd40b/k8s-windows-node-rsrc-use"
    }
   ]
  },
  {
   "title": "Net Saturation (Dropped)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (\n                (irate(windows_net_packets_received_discarded_total{cluster=\"$cluster\", job=\"windows-exporter\"}[1m]) +\n                irate(windows_net_packets_outbound_discarded_total{cluster=\"$cluster\", job=\"windows-exporter\"}[1m]))\n              )",
     "legendFormat": "{{instance}}",
     "legendLink": "./d/96e7484b0bb53b74fbc2bcb7723cd40b/k8s-windows-node-rsrc-use"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Disk Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(max by (instance,volume)(\n                (windows_logical_disk_size_bytes{cluster=\"$cluster\", job=\"windows-exporter\"}\n              - windows_logical_disk_free_bytes{cluster=\"$cluster\", job=\"windows-exporter\"})\n              / windows_logical_disk_size_bytes{cluster=\"$cluster\", job=\"windows-exporter\"}\n              ))\n",
     "legendFormat": "{{instance}}",
     "legendLink": "./d/96e7484b0bb53b74fbc2bcb7723cd40b/k8s-windows-node-rsrc-use"
    }
   ]
  }
 ]
}