
[bool]$enabled = $true
Set-AzContext -Subscription 5a9b24b3-4658-4e41-b650-762cc0026438

$cluster = "azmon-prod-1p-weu-0"
New-AzResourceGroupDeployment  -ResourceGroupName CommonInfraTestRules -TemplateFile DefaultAlerts.json -enabled $enabled -clusterName $cluster -location northcentralus -macResourceId "/subscriptions/1bfea79d-7198-4d9f-8846-24a8cfa5d97d/resourceGroups/commoninfra-prod-azuremonitorworkspace/providers/microsoft.monitor/accounts/commoninfra-prod-metrics-insights"
New-AzResourceGroupDeployment  -ResourceGroupName CommonInfraTestRules -TemplateFile v3_DefaultAlerts.json -enabled $enabled -clusterName $cluster -location northcentralus -azureMonitorWorkspaceResourceId "/subscriptions/1bfea79d-7198-4d9f-8846-24a8cfa5d97d/resourceGroups/commoninfra-prod-azuremonitorworkspace/providers/microsoft.monitor/accounts/commoninfra-prod-metrics-insights"
 New-AzResourceGroupDeployment  -ResourceGroupName CommonInfraTestRules -TemplateFile ci_recommended_alerts.json -enabled $enabled -clusterName $cluster -location northcentralus -macResourceId "/subscriptions/1bfea79d-7198-4d9f-8846-24a8cfa5d97d/resourceGroups/commoninfra-prod-azuremonitorworkspace/providers/microsoft.monitor/accounts/commoninfra-prod-metrics-insights"
 New-AzResourceGroupDeployment  -ResourceGroupName CommonInfraTestRules -TemplateFile v3_ci_recommended_alerts.json -enabled $enabled -clusterName $cluster -location northcentralus -azureMonitorWorkspaceResourceId "/subscriptions/1bfea79d-7198-4d9f-8846-24a8cfa5d97d/resourceGroups/commoninfra-prod-azuremonitorworkspace/providers/microsoft.monitor/accounts/commoninfra-prod-metrics-insights"


$cluster = "azmon-prod-eus-0"
New-AzResourceGroupDeployment  -ResourceGroupName CommonInfraTestRules -TemplateFile DefaultAlerts.json -enabled $enabled -clusterName $cluster -location northcentralus -macResourceId "/subscriptions/1bfea79d-7198-4d9f-8846-24a8cfa5d97d/resourceGroups/commoninfra-prod-azuremonitorworkspace/providers/microsoft.monitor/accounts/commoninfra-prod-metrics-insights"
New-AzResourceGroupDeployment  -ResourceGroupName CommonInfraTestRules -TemplateFile v3_DefaultAlerts.json -enabled $enabled -clusterName $cluster -location northcentralus -azureMonitorWorkspaceResourceId "/subscriptions/1bfea79d-7198-4d9f-8846-24a8cfa5d97d/resourceGroups/commoninfra-prod-azuremonitorworkspace/providers/microsoft.monitor/accounts/commoninfra-prod-metrics-insights"
New-AzResourceGroupDeployment  -ResourceGroupName CommonInfraTestRules -TemplateFile ci_recommended_alerts.json -enabled $enabled -clusterName $cluster -location northcentralus -macResourceId "/subscriptions/1bfea79d-7198-4d9f-8846-24a8cfa5d97d/resourceGroups/commoninfra-prod-azuremonitorworkspace/providers/microsoft.monitor/accounts/commoninfra-prod-metrics-insights"
New-AzResourceGroupDeployment  -ResourceGroupName CommonInfraTestRules -TemplateFile v3_ci_recommended_alerts.json -enabled $enabled -clusterName $cluster -location northcentralus -azureMonitorWorkspaceResourceId "/subscriptions/1bfea79d-7198-4d9f-8846-24a8cfa5d97d/resourceGroups/commoninfra-prod-azuremonitorworkspace/providers/microsoft.monitor/accounts/commoninfra-prod-metrics-insights"

$cluster = "azmon-prod-cus-0"
New-AzResourceGroupDeployment  -ResourceGroupName CommonInfraTestRules -TemplateFile DefaultAlerts.json -enabled $enabled -clusterName $cluster -location northcentralus -macResourceId "/subscriptions/1bfea79d-7198-4d9f-8846-24a8cfa5d97d/resourceGroups/commoninfra-prod-azuremonitorworkspace/providers/microsoft.monitor/accounts/commoninfra-prod-metrics-insights"
New-AzResourceGroupDeployment  -ResourceGroupName CommonInfraTestRules -TemplateFile v3_DefaultAlerts.json -enabled $enabled -clusterName $cluster -location northcentralus -azureMonitorWorkspaceResourceId "/subscriptions/1bfea79d-7198-4d9f-8846-24a8cfa5d97d/resourceGroups/commoninfra-prod-azuremonitorworkspace/providers/microsoft.monitor/accounts/commoninfra-prod-metrics-insights"
New-AzResourceGroupDeployment  -ResourceGroupName CommonInfraTestRules -TemplateFile ci_recommended_alerts.json -enabled $enabled -clusterName $cluster -location northcentralus -macResourceId "/subscriptions/1bfea79d-7198-4d9f-8846-24a8cfa5d97d/resourceGroups/commoninfra-prod-azuremonitorworkspace/providers/microsoft.monitor/accounts/commoninfra-prod-metrics-insights"
New-AzResourceGroupDeployment  -ResourceGroupName CommonInfraTestRules -TemplateFile v3_ci_recommended_alerts.json -enabled $enabled -clusterName $cluster -location northcentralus -azureMonitorWorkspaceResourceId "/subscriptions/1bfea79d-7198-4d9f-8846-24a8cfa5d97d/resourceGroups/commoninfra-prod-azuremonitorworkspace/providers/microsoft.monitor/accounts/commoninfra-prod-metrics-insights"
