# scrape_configs:
#   - job_name: prometheus_ref_app_etcd
#     scheme: http
#     scrape_interval: $$SCRAPE_INTERVAL$$
#     kubernetes_sd_configs:
#     - role: pod
#     relabel_configs:
#     - source_labels: [__meta_kubernetes_pod_label_app]
#       action: keep
#       regex: "prometheus-reference-app"
scrape_configs:
- job_name: controlplane-etcd
  scrape_interval: $$SCRAPE_INTERVAL$$
  follow_redirects: false
  scheme: https
  kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
          - $$POD_NAMESPACE$$
  tls_config:
    ca_file: /etc/kubernetes/secrets/etcd-client-ca.crt
    cert_file: /etc/kubernetes/secrets/etcd-client.crt
    key_file: /etc/kubernetes/secrets/etcd-client.key
    insecure_skip_verify: true
  relabel_configs:
    - source_labels: [ __meta_kubernetes_service_label_app, __meta_kubernetes_pod_container_port_number ]
      action: keep
      regex: etcd;2379
    - source_labels: [ __meta_kubernetes_pod_name ]
      regex: (.*)
      target_label: instance
      action: replace
    - source_labels: [ __meta_kubernetes_pod_name ]
      action: drop
      regex: (etcd2-.*)
  metric_relabel_configs:
    - source_labels: [ host ]
      action: hashmod
      modulus: 10000000000000000000 # take last 19 digits of the MD5 hash. (Prom won't let us take more than this)
      target_label: hostalias
    - source_labels: [ host ]
      regex: ^hcp-kubernetes.*.svc.cluster.local:443$
      target_label: hostalias
      replacement: kube-apiserver
    - source_labels: [ hostalias ]
      action: replace
      target_label: host
    - source_labels: [ __name__ ]
      action: drop
      regex: (go_.*|process_(cpu|max|resident|virtual|open)_.*)
    - action: labeldrop
      regex: hostalias