  scrape_configs:
  - job_name: kube-controller-manager
    scrape_interval: $$SCRAPE_INTERVAL$$
    follow_redirects: false
    scheme: https
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - $$POD_NAMESPACE$$
    tls_config:
      ca_file: /etc/kubernetes/secrets/ca.pem
      cert_file: /etc/kubernetes/secrets/client.pem
      key_file: /etc/kubernetes/secrets/client-key.pem
      insecure_skip_verify: true
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_k8s_app, __meta_kubernetes_pod_container_name]
        action: keep
        regex: kube-controller-manager;kube-controller-manager
      - source_labels: [__meta_kubernetes_pod_annotation_aks_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_aks_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [ __address__, __meta_kubernetes_pod_annotation_aks_prometheus_io_port ]
        action: replace
        separator: ":"
        target_label: __address__
      - source_labels: [__meta_kubernetes_pod_name]
        regex: (.*)
        target_label: pod
        action: replace
