  scrape_configs:
  - job_name: node
    scheme: http
    scrape_interval: 30s
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
       names:
       - $$POD_NAMESPACE$$
    relabel_configs:
    - action: keep
      source_labels: [__meta_kubernetes_endpoints_name]
      regex: $$NODE_EXPORTER_NAME$$
