  scrape_configs:
  - job_name: node
    scheme: http
    scrape_interval: $$SCRAPE_INTERVAL$$
    label_limit: 63
    label_name_length_limit: 511
    label_value_length_limit: 1023
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
       names:
       - $$POD_NAMESPACE$$
    relabel_configs:
    - action: keep
      source_labels: [__meta_kubernetes_endpoints_name]
      regex: $$NODE_EXPORTER_NAME$$
    - source_labels: [__metrics_path__]
      regex: (.*)
      target_label: metrics_path
    - source_labels: [__meta_kubernetes_endpoint_node_name]
      regex: (.*)
      target_label: instance
