 scrape_configs:
 - job_name: storage-operator-control-plane
   honor_labels: true
   scrape_interval: $$SCRAPE_INTERVAL$$
   scheme: http
   kubernetes_sd_configs:
     - role: pod
       namespaces:
         names:
           - kube-system
   relabel_configs:
     - source_labels: [__meta_kubernetes_namespace]
       action: keep
       regex: kube-system
     - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_component]
       action: keep
       regex: csi-local-node
     - source_labels: [__meta_kubernetes_pod_container_port_name]
       action: keep
       regex: metrics
     - source_labels: [__meta_kubernetes_pod_node_name]
       action: keep
       regex: $$NODE_NAME$$