scrape_configs:
- job_name: windows-exporter
  scheme: http
  scrape_interval: 30s
  relabel_configs:
  - source_labels: [__address__]
    replacement: '$NODE_NAME'
    target_label: instance
  static_configs:
  - targets: ['$NODE_IP:9182']

- job_name: kube-proxy-windows
  scheme: http
  scrape_interval: 30s
  relabel_configs:
  - source_labels: [__address__]
    replacement: '$NODE_NAME'
    target_label: instance
  static_configs:
  - targets: ['$NODE_IP:10249']

- job_name: kubelet
  scheme: https
  metrics_path: /metrics
  scrape_interval: 30s
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  relabel_configs:
  - source_labels: [__metrics_path__]
    regex: (.*)
    target_label: metrics_path
  - source_labels: [__address__]
    replacement: '$NODE_NAME'
    target_label: instance
  - source_labels: [__address__]
    replacement: '$OS_TYPE'
    target_label: "kubernetes_io_os"
  static_configs:
  - targets: ['$NODE_IP:10250']

- job_name: prometheus_collector_health
  static_configs:
  - targets: ['127.0.0.1:2234']
