{
 "title": "Nodes (Node exporter)",
 "description": "Source-https://github.com/monitoring-mixins/website/blob/master/assets/node-exporter/dashboards/nodes.json",
 "tags": [ "node exporter" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"node\"},cluster)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_exporter_build_info{job=\"node\",cluster=~\"$cluster\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  (1 - rate(node_cpu_seconds_total{job=~\"node\", mode=~\"idle\", instance=~\"$instance\",cluster=~\"$cluster\"}[$__rate_interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=~\"node\", mode=~\"idle\", instance=~\"$instance\",cluster=~\"$cluster\"})\n)\n",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=~\"node\", instance=~\"$instance\",cluster=~\"$cluster\"}",
     "legendFormat": "1m load average"
    },
    {
     "expr": "node_load5{job=~\"node\", instance=~\"$instance\",cluster=~\"$cluster\"}",
     "legendFormat": "5m load average"
    },
    {
     "expr": "node_load15{job=~\"node\", instance=~\"$instance\",cluster=~\"$cluster\"}",
     "legendFormat": "15m load average"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=~\"node\", instance=~\"$instance\", mode=~\"idle\",cluster=~\"$cluster\"})",
     "legendFormat": "logical cores"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=~\"node\", instance=~\"$instance\",cluster=~\"$cluster\"}\n-\n  node_memory_MemFree_bytes{job=~\"node\", instance=~\"$instance\",cluster=~\"$cluster\"}\n-\n  node_memory_Buffers_bytes{job=~\"node\", instance=~\"$instance\",cluster=~\"$cluster\"}\n-\n  node_memory_Cached_bytes{job=~\"node\", instance=~\"$instance\",cluster=~\"$cluster\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node\", instance=\"$instance\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node\", instance=\"$instance\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node\", instance=\"$instance\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 -\n(\n  avg(node_memory_MemAvailable_bytes{job=~\"node\", instance=~\"$instance\",cluster=~\"$cluster\"})\n/\n  avg(node_memory_MemTotal_bytes{job=~\"node\", instance=~\"$instance\",cluster=~\"$cluster\"})\n* 100\n)\n"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=~\"node\", instance=~\"$instance\", device!=\"\",cluster=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{job=~\"node\", instance=~\"$instance\", device!=\"\",cluster=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{device}} written"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=~\"node\", instance=~\"$instance\", device!=\"\",cluster=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{device}} io time"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  max by (device) (\n    node_filesystem_size_bytes{job=~\"node\", instance=~\"$instance\", fstype!=\"\",cluster=~\"$cluster\"}\n  -\n    node_filesystem_avail_bytes{job=~\"node\", instance=~\"$instance\", fstype!=\"\",cluster=~\"$cluster\"}\n  )\n)\n",
     "legendFormat": "used"
    },
    {
     "expr": "sum(\n  max by (device) (\n    node_filesystem_avail_bytes{job=\"node\", instance=\"$instance\", fstype!=\"\"}\n  )\n)\n",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=~\"node\", instance=~\"$instance\", device!=\"lo\",cluster=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=~\"node\", instance=~\"$instance\", device!=\"lo\",cluster=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}