{
 "title": "USE Method / Node (Node exporter)",
 "description": "Source-https://github.com/monitoring-mixins/website/blob/master/assets/node-exporter/dashboards/node-rsrc-use.json",
 "tags": [ "node exporter" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_filesystem_size_bytes{job=\"node\"},cluster)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(node_filesystem_size_bytes{job=\"node\",cluster=~\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "\r 1 - avg without (cpu, mode) (\r\n                rate(node_cpu_seconds_total{job=~\"node\", cluster=~\"$cluster\",instance=~\"$instance\", mode=~\"idle\"}[5m]))",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "CPU Saturation (Load1 per CPU)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "  (\r\n                node_load1{job=~\"node\", instance=~\"$instance\",cluster=~\"$cluster\"}\r\n              /\r\n                count without (cpu) (\r\n                count without (mode) (\r\n                  node_cpu_seconds_total{job=~\"node\", instance=~\"$instance\",cluster=~\"$cluster\"}\r\n                )\r\n              )\r\n              ) ",
     "legendFormat": "Saturation"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "  1 - (node_memory_MemAvailable_bytes{job=\"node\",instance=~\"$instance\",cluster=~\"$cluster\"}\n   /\r\n       node_memory_MemTotal_bytes{job=\"node\", instance=~\"$instance\",cluster=~\"$cluster\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Memory Saturation (Major Page Faults)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pgmajfault{job=~\"node\", instance=~\"$instance\",cluster=~\"$cluster\"}[5m])",
     "legendFormat": "Major page faults"
    }
   ]
  },
  { "title": "Net", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Net Utilisation (Bytes Receive/Transmit)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum without (device) (\r\n                rate(node_network_receive_bytes_total{job=~\"node\", instance=~\"$instance\",cluster=~\"$cluster\", device!=\"lo\"}[5m])\r\n              )",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum without (device) (\r\n                rate(node_network_transmit_bytes_total{job=~\"node\", instance=~\"$instance\",cluster=~\"$cluster\", device!=\"lo\"}[5m])\r\n              )",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Net Saturation (Drops Receive/Transmit)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum without (device) (\r\n          rate(node_network_receive_drop_total{job=~\"node\", device!=\"lo\",job=~\"node\", instance=~\"$instance\",cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "Receive drops"
    },
    {
     "expr": "sum without (device) (\r\n                rate(node_network_transmit_drop_total{job=~\"node\", instance=~\"$instance\", cluster=~\"$cluster\",device!=\"lo\"}[5m])\r\n              )",
     "legendFormat": "Transmit drops"
    }
   ]
  },
  { "title": "Disk IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Disk IO Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=~\"node\",instance=~\"$instance\",device=~\"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", cluster=~\"$cluster\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk IO Saturation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total{job=~\"node\",instance=~\"$instance\", cluster=~\"$cluster\",device=~\"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Disk Space", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Disk Space Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 -\n(\n  max without (mountpoint, fstype) (node_filesystem_avail_bytes{job=~\"node\", fstype!=\"\", instance=~\"$instance\",cluster=~\"$cluster\"})\n/\n  max without (mountpoint, fstype) (node_filesystem_size_bytes{job=~\"node\", fstype!=\"\", instance=~\"$instance\",cluster=~\"$cluster\"})\n)\n",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}