{
 "title": "USE Method / Cluster (Node exporter)",
 "description": "Source-https://github.com/monitoring-mixins/website/blob/master/assets/node-exporter/dashboards/node-cluster-rsrc-use.json",
 "tags": [ "node exporter" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_filesystem_size_bytes{job=\"node\"},cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  1 - avg without (cpu, mode) (\r\n          rate(node_cpu_seconds_total{job=~\"node\", mode=~\"idle\", cluster=~\"$cluster\"}[5m])\r\n        )\n*\n  count without (cpu) (\r\n          count without (mode) (\r\n            node_cpu_seconds_total{job=~\"node\", cluster=~\"$cluster\"}\r\n          )\r\n        )\n)\n/ scalar(sum(count without (cpu) (\r\n          count without (mode) (\r\n            node_cpu_seconds_total{job=~\"node\", cluster=~\"$cluster\"}\r\n          )\r\n        )))\n",
     "legendFormat": "{{instance}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "CPU Saturation (load1 per CPU)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_load1{job=~\"node\", cluster=~\"$cluster\"} /  count without (cpu) (count without (mode) (node_cpu_seconds_total{job=~\"node\", cluster=~\"$cluster\"})))\n/\nscalar(count(  (node_load1{job=~\"node\", cluster=~\"$cluster\"} /  count without (cpu) (count without (mode) (node_cpu_seconds_total{job=~\"node\", cluster=~\"$cluster\"})))))\n",
     "legendFormat": "{{instance}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": " 1 - (node_memory_MemAvailable_bytes{job=~\"node\", cluster=~\"$cluster\"}  / node_memory_MemTotal_bytes{job=~\"node\", cluster=~\"$cluster\"})\n/ scalar(count( 1 - ( node_memory_MemAvailable_bytes{job=~\"node\", cluster=~\"$cluster\"}  / node_memory_MemTotal_bytes{job=~\"node\", cluster=~\"$cluster\"})))\n",
     "legendFormat": "{{instance}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "Memory Saturation (Major Page Faults)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pgmajfault{job=~\"node\", cluster=~\"$cluster\"}[5m])",
     "legendFormat": "{{instance}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Net Utilisation (Bytes Receive/Transmit)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum without (device) (\r\n                rate(node_network_receive_bytes_total{job=~\"node\", device!=\"lo\", cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "{{instance}} Receive",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    },
    {
     "expr": "sum without (device) (\r\n                rate(node_network_transmit_bytes_total{job=~\"node\", device!=\"lo\", cluster=~\"$cluster\"}[5m])\r\n              )",
     "legendFormat": "{{instance}} Transmit",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "Net Saturation (Drops Receive/Transmit)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum without (device) (\r\n                rate(node_network_receive_drop_total{job=~\"node\", device!=\"lo\", cluster=~\"$cluster\"}[5m])\r\n              )",
     "legendFormat": "{{instance}} Receive",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    },
    {
     "expr": "sum without (device) (\r\n                rate(node_network_transmit_drop_total{job=~\"node\", device!=\"lo\", cluster=~\"$cluster\"}[5m])\r\n              )",
     "legendFormat": "{{instance}} Transmit",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  { "title": "Disk IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Disk IO Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=~\"node\", device=~\"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\",cluster=~\"$cluster\"}[5m])\n/ scalar(count(rate(node_disk_io_time_seconds_total{job=~\"node\", device=~\"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", cluster=~\"$cluster\"}[5m])))\n",
     "legendFormat": "{{instance}} {{device}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  {
   "title": "Disk IO Saturation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total{job=~\"node\", device=~\"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\",cluster=\"$cluster\"}[5m])\n/ scalar(count(rate(node_disk_io_time_weighted_seconds_total{job=~\"node\", device=~\"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", cluster=~\"$cluster\"}[5m])))",
     "legendFormat": "{{instance}} {{device}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  },
  { "title": "Disk Space", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Disk Space Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum without (device) (\n  max without (fstype, mountpoint) (\n    node_filesystem_size_bytes{job=~\"node\", fstype!=\"\"} - node_filesystem_avail_bytes{job=~\"node\", fstype!=\"\",cluster=\"$cluster\"}\n  )\n) \n/ scalar(sum(max without (fstype, mountpoint) (node_filesystem_size_bytes{job=~\"node\", fstype!=\"\",cluster=~\"$cluster\"})))\n",
     "legendFormat": "{{instance}}",
     "legendLink": "/dashboard/file/node-rsrc-use.json"
    }
   ]
  }
 ]
}