# See results in the tab Security > Code scanning alerts
name: run-sdl-code-analysis-tools
on: workflow_dispatch
jobs:
  run-sdl-code-analysis-tools:
    runs-on: ubuntu-latest
    steps:
      - name: Set-workflow-initiator
        run: echo "Initiated by - ${GITHUB_ACTOR}"
      - name: Initialize-CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go, javascript, ruby
      - name: Checkout-code
        uses: actions/checkout@v3
      - name: Install-build-dependencies
        run: sudo apt-get install build-essential -y
      - name: Build-source-code
        run: cd ./otelcollector/opentelemetry-collector-builder/ && make
      # Check the output of this step to see if there are any alerts, the sarif is missing properties required by github:
      # https://github.com/microsoft/binskim/issues/509
      - name: BinSkim Scan
        run: dotnet tool install --global Microsoft.CodeAnalysis.BinSkim --version 1.7.1 && binskim analyze ./otelcollector/opentelemetry-collector-builder/otelcollector ./otelcollector/prom-config-validator-builder/promconfigvalidator ./otelcollector/fluent-bit/src/out_appinsights.so
      - name: DevSkim Scan
        uses: microsoft/DevSkim-Action@v1
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          output: ./
          upload: "false"
      - name: Upload SDL Tool Results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: /home/runner/work/prometheus-collector/prometheus-collector
