name: size-label #https://github.com/kubernetes/kubernetes/labels?q=size
on:
  pull_request_target:
    branches:
      - main
jobs:
  size-label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: size-label
        uses: "pascalgn/size-label-action@56b489b027932ec0cf60438a1a5f1a19c8fc71ff" # v0.5.7
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
