name: build-and-push-image
on:
  push:
    branches:
      vishwa/test
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set-image-tag-prefix-dev
        run: echo "IMAGE_TAG_PREFIX_DEV=containerinsightsprod.azurecr.io/public/azuremonitor/containerinsights/cidev" >> $GITHUB_ENV
      - name: Set-image-tag-suffix
        run: echo "IMAGE_TAG_DATE=$(date +%m-%d-%Y)" >> $GITHUB_ENV
      - name: Set-image-tag-name
        run: echo "IMAGE_TAG_NAME=prometheus-collector" >> $GITHUB_ENV
      - name: Checkout-code
        uses: actions/checkout@v2
      - name: Install-golang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.1'
      - name: Show-versions-(On-build-machine)
        run: lsb_release -a && go version
      - name: Install-build-dependencies
        run: sudo apt-get install build-essential -y
      - name: show-cur-dir
        run: pwd
      - name: show-ls
        run: ls -al
      - name: Build-the-thing
        run: cd ./otelcollector/opentelemetry-collector-builder/ && make
      - name: Create-container-image
        run: |
            cd ./otelcollector/ && docker build . --file Dockerfile -t $IMAGE_TAG_PREFIX_DEV:$IMAGE_TAG_NAME-$IMAGE_TAG_DATE-${GITHUB_SHA::8} --build-arg IMAGE_TAG=$IMAGE_TAG_NAME-$IMAGE_TAG_DATE-${GITHUB_SHA::8}
      - name: list-docker-images
        run: docker images
      - name: Run-trivy-scanner-on-image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: $IMAGE_TAG_PREFIX_DEV:$IMAGE_TAG_NAME-$IMAGE_TAG_DATE-${GITHUB_SHA::8}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
